package com.stock.info.dao;

import com.stock.info.domain.entity.StkFinanceMainbz;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import java.util.List;


@Mapper
@Repository
public interface StkFinanceMainbzMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stk_finance_mainbz
     *
     * @mbggenerated
     */
    int insert(StkFinanceMainbz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stk_finance_mainbz
     *
     * @mbggenerated
     */
    List<StkFinanceMainbz> selectAll();


    /**
     * 删除数据根据证券code
     * @param code
     */
    void deleteByCode(String code);
}