package com.stock.info.dao;

import com.stock.info.domain.entity.StkFinanceBanlancesheet;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import java.util.List;


@Mapper
@Repository
public interface StkFinanceBanlancesheetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stk_finance_banlancesheet
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stk_finance_banlancesheet
     *
     * @mbggenerated
     */
    int insert(StkFinanceBanlancesheet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stk_finance_banlancesheet
     *
     * @mbggenerated
     */
    StkFinanceBanlancesheet selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stk_finance_banlancesheet
     *
     * @mbggenerated
     */
    List<StkFinanceBanlancesheet> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stk_finance_banlancesheet
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StkFinanceBanlancesheet record);


    /**
     * 删除资产负债表根据code代码
     * @param code
     */
    void deleteByCode(String code);
}