package com.stock.info.dao;

import com.stock.info.domain.entity.StkFinanceCashflow;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import java.util.List;


@Mapper
@Repository
public interface StkFinanceCashflowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stk_finance_cashflow
     *
     * @mbggenerated
     */
    int insert(StkFinanceCashflow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stk_finance_cashflow
     *
     * @mbggenerated
     */
    List<StkFinanceCashflow> selectAll();


    /**
     * 删除根据code
     * @param code
     */
    void deleteByCode(String code);
}