package com.stock.info.dao;

import com.stock.info.domain.entity.StkFinanceIndicator;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import java.util.List;


@Mapper
@Repository
public interface StkFinanceIndicatorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stk_finance_indicator
     *
     * @mbggenerated
     */
    int insert(StkFinanceIndicator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stk_finance_indicator
     *
     * @mbggenerated
     */
    List<StkFinanceIndicator> selectAll();


    /**
     * 根据股票代码删除数据
     * @param code
     */
    void deleteByCode(String code);
}