package com.stock.info.domain.entity;

import java.io.Serializable;
import java.math.BigDecimal;

public class StkFinanceCashflow implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.ts_code
     *
     * @mbggenerated
     */
    private String tsCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.ann_date
     *
     * @mbggenerated
     */
    private String annDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.f_ann_date
     *
     * @mbggenerated
     */
    private String fAnnDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.end_date
     *
     * @mbggenerated
     */
    private String endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.report_type
     *
     * @mbggenerated
     */
    private String reportType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.comp_type
     *
     * @mbggenerated
     */
    private String compType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.net_profit
     *
     * @mbggenerated
     */
    private BigDecimal netProfit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.finan_exp
     *
     * @mbggenerated
     */
    private BigDecimal finanExp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.c_fr_sale_sg
     *
     * @mbggenerated
     */
    private BigDecimal cFrSaleSg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.recp_tax_rends
     *
     * @mbggenerated
     */
    private BigDecimal recpTaxRends;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.n_depos_incr_fi
     *
     * @mbggenerated
     */
    private BigDecimal nDeposIncrFi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.n_incr_loans_cb
     *
     * @mbggenerated
     */
    private BigDecimal nIncrLoansCb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.n_inc_borr_oth_fi
     *
     * @mbggenerated
     */
    private BigDecimal nIncBorrOthFi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.prem_fr_orig_contr
     *
     * @mbggenerated
     */
    private BigDecimal premFrOrigContr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.n_incr_insured_dep
     *
     * @mbggenerated
     */
    private BigDecimal nIncrInsuredDep;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.n_reinsur_prem
     *
     * @mbggenerated
     */
    private BigDecimal nReinsurPrem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.n_incr_disp_tfa
     *
     * @mbggenerated
     */
    private BigDecimal nIncrDispTfa;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.ifc_cash_incr
     *
     * @mbggenerated
     */
    private BigDecimal ifcCashIncr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.n_incr_disp_faas
     *
     * @mbggenerated
     */
    private BigDecimal nIncrDispFaas;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.n_incr_loans_oth_bank
     *
     * @mbggenerated
     */
    private BigDecimal nIncrLoansOthBank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.n_cap_incr_repur
     *
     * @mbggenerated
     */
    private BigDecimal nCapIncrRepur;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.c_fr_oth_operate_a
     *
     * @mbggenerated
     */
    private BigDecimal cFrOthOperateA;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.c_inf_fr_operate_a
     *
     * @mbggenerated
     */
    private BigDecimal cInfFrOperateA;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.c_paid_goods_s
     *
     * @mbggenerated
     */
    private BigDecimal cPaidGoodsS;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.c_paid_to_for_empl
     *
     * @mbggenerated
     */
    private BigDecimal cPaidToForEmpl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.c_paid_for_taxes
     *
     * @mbggenerated
     */
    private BigDecimal cPaidForTaxes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.n_incr_clt_loan_adv
     *
     * @mbggenerated
     */
    private BigDecimal nIncrCltLoanAdv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.n_incr_dep_cbob
     *
     * @mbggenerated
     */
    private BigDecimal nIncrDepCbob;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.c_pay_claims_orig_inco
     *
     * @mbggenerated
     */
    private BigDecimal cPayClaimsOrigInco;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.pay_handling_chrg
     *
     * @mbggenerated
     */
    private BigDecimal payHandlingChrg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.pay_comm_insur_plcy
     *
     * @mbggenerated
     */
    private BigDecimal payCommInsurPlcy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.oth_cash_pay_oper_act
     *
     * @mbggenerated
     */
    private BigDecimal othCashPayOperAct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.st_cash_out_act
     *
     * @mbggenerated
     */
    private BigDecimal stCashOutAct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.n_cashflow_act
     *
     * @mbggenerated
     */
    private BigDecimal nCashflowAct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.oth_recp_ral_inv_act
     *
     * @mbggenerated
     */
    private BigDecimal othRecpRalInvAct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.c_disp_withdrwl_invest
     *
     * @mbggenerated
     */
    private BigDecimal cDispWithdrwlInvest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.c_recp_return_invest
     *
     * @mbggenerated
     */
    private BigDecimal cRecpReturnInvest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.n_recp_disp_fiolta
     *
     * @mbggenerated
     */
    private BigDecimal nRecpDispFiolta;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.n_recp_disp_sobu
     *
     * @mbggenerated
     */
    private BigDecimal nRecpDispSobu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.stot_inflows_inv_act
     *
     * @mbggenerated
     */
    private BigDecimal stotInflowsInvAct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.c_pay_acq_const_fiolta
     *
     * @mbggenerated
     */
    private BigDecimal cPayAcqConstFiolta;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.c_paid_invest
     *
     * @mbggenerated
     */
    private BigDecimal cPaidInvest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.n_disp_subs_oth_biz
     *
     * @mbggenerated
     */
    private BigDecimal nDispSubsOthBiz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.oth_pay_ral_inv_act
     *
     * @mbggenerated
     */
    private BigDecimal othPayRalInvAct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.n_incr_pledge_loan
     *
     * @mbggenerated
     */
    private BigDecimal nIncrPledgeLoan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.stot_out_inv_act
     *
     * @mbggenerated
     */
    private BigDecimal stotOutInvAct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.n_cashflow_inv_act
     *
     * @mbggenerated
     */
    private BigDecimal nCashflowInvAct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.c_recp_borrow
     *
     * @mbggenerated
     */
    private BigDecimal cRecpBorrow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.proc_issue_bonds
     *
     * @mbggenerated
     */
    private BigDecimal procIssueBonds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.oth_cash_recp_ral_fnc_act
     *
     * @mbggenerated
     */
    private BigDecimal othCashRecpRalFncAct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.stot_cash_in_fnc_act
     *
     * @mbggenerated
     */
    private BigDecimal stotCashInFncAct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.free_cashflow
     *
     * @mbggenerated
     */
    private BigDecimal freeCashflow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.c_prepay_amt_borr
     *
     * @mbggenerated
     */
    private BigDecimal cPrepayAmtBorr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.c_pay_dist_dpcp_int_exp
     *
     * @mbggenerated
     */
    private BigDecimal cPayDistDpcpIntExp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.incl_dvd_profit_paid_sc_ms
     *
     * @mbggenerated
     */
    private BigDecimal inclDvdProfitPaidScMs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.oth_cashpay_ral_fnc_act
     *
     * @mbggenerated
     */
    private BigDecimal othCashpayRalFncAct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.stot_cashout_fnc_act
     *
     * @mbggenerated
     */
    private BigDecimal stotCashoutFncAct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.n_cash_flows_fnc_act
     *
     * @mbggenerated
     */
    private BigDecimal nCashFlowsFncAct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.eff_fx_flu_cash
     *
     * @mbggenerated
     */
    private BigDecimal effFxFluCash;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.n_incr_cash_cash_equ
     *
     * @mbggenerated
     */
    private BigDecimal nIncrCashCashEqu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.c_cash_equ_beg_period
     *
     * @mbggenerated
     */
    private BigDecimal cCashEquBegPeriod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.c_cash_equ_end_period
     *
     * @mbggenerated
     */
    private BigDecimal cCashEquEndPeriod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.c_recp_cap_contrib
     *
     * @mbggenerated
     */
    private BigDecimal cRecpCapContrib;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.incl_cash_rec_saims
     *
     * @mbggenerated
     */
    private BigDecimal inclCashRecSaims;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.uncon_invest_loss
     *
     * @mbggenerated
     */
    private BigDecimal unconInvestLoss;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.prov_depr_assets
     *
     * @mbggenerated
     */
    private BigDecimal provDeprAssets;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.depr_fa_coga_dpba
     *
     * @mbggenerated
     */
    private BigDecimal deprFaCogaDpba;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.amort_intang_assets
     *
     * @mbggenerated
     */
    private BigDecimal amortIntangAssets;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.lt_amort_deferred_exp
     *
     * @mbggenerated
     */
    private BigDecimal ltAmortDeferredExp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.decr_deferred_exp
     *
     * @mbggenerated
     */
    private BigDecimal decrDeferredExp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.incr_acc_exp
     *
     * @mbggenerated
     */
    private BigDecimal incrAccExp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.loss_disp_fiolta
     *
     * @mbggenerated
     */
    private BigDecimal lossDispFiolta;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.loss_scr_fa
     *
     * @mbggenerated
     */
    private BigDecimal lossScrFa;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.loss_fv_chg
     *
     * @mbggenerated
     */
    private BigDecimal lossFvChg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.invest_loss
     *
     * @mbggenerated
     */
    private BigDecimal investLoss;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.decr_def_inc_tax_assets
     *
     * @mbggenerated
     */
    private BigDecimal decrDefIncTaxAssets;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.incr_def_inc_tax_liab
     *
     * @mbggenerated
     */
    private BigDecimal incrDefIncTaxLiab;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.decr_inventories
     *
     * @mbggenerated
     */
    private BigDecimal decrInventories;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.decr_oper_payable
     *
     * @mbggenerated
     */
    private BigDecimal decrOperPayable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.incr_oper_payable
     *
     * @mbggenerated
     */
    private BigDecimal incrOperPayable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.others
     *
     * @mbggenerated
     */
    private BigDecimal others;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.im_net_cashflow_oper_act
     *
     * @mbggenerated
     */
    private BigDecimal imNetCashflowOperAct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.conv_debt_into_cap
     *
     * @mbggenerated
     */
    private BigDecimal convDebtIntoCap;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.conv_copbonds_due_within_1y
     *
     * @mbggenerated
     */
    private BigDecimal convCopbondsDueWithin1y;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.fa_fnc_leases
     *
     * @mbggenerated
     */
    private BigDecimal faFncLeases;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.end_bal_cash
     *
     * @mbggenerated
     */
    private BigDecimal endBalCash;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.beg_bal_cash
     *
     * @mbggenerated
     */
    private BigDecimal begBalCash;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.end_bal_cash_equ
     *
     * @mbggenerated
     */
    private BigDecimal endBalCashEqu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.beg_bal_cash_equ
     *
     * @mbggenerated
     */
    private BigDecimal begBalCashEqu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.im_n_incr_cash_equ
     *
     * @mbggenerated
     */
    private BigDecimal imNIncrCashEqu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_cashflow.update_flag
     *
     * @mbggenerated
     */
    private String updateFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table stk_finance_cashflow
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.ts_code
     *
     * @return the value of stk_finance_cashflow.ts_code
     *
     * @mbggenerated
     */
    public String getTsCode() {
        return tsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.ts_code
     *
     * @param tsCode the value for stk_finance_cashflow.ts_code
     *
     * @mbggenerated
     */
    public void setTsCode(String tsCode) {
        this.tsCode = tsCode == null ? null : tsCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.ann_date
     *
     * @return the value of stk_finance_cashflow.ann_date
     *
     * @mbggenerated
     */
    public String getAnnDate() {
        return annDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.ann_date
     *
     * @param annDate the value for stk_finance_cashflow.ann_date
     *
     * @mbggenerated
     */
    public void setAnnDate(String annDate) {
        this.annDate = annDate == null ? null : annDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.f_ann_date
     *
     * @return the value of stk_finance_cashflow.f_ann_date
     *
     * @mbggenerated
     */
    public String getfAnnDate() {
        return fAnnDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.f_ann_date
     *
     * @param fAnnDate the value for stk_finance_cashflow.f_ann_date
     *
     * @mbggenerated
     */
    public void setfAnnDate(String fAnnDate) {
        this.fAnnDate = fAnnDate == null ? null : fAnnDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.end_date
     *
     * @return the value of stk_finance_cashflow.end_date
     *
     * @mbggenerated
     */
    public String getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.end_date
     *
     * @param endDate the value for stk_finance_cashflow.end_date
     *
     * @mbggenerated
     */
    public void setEndDate(String endDate) {
        this.endDate = endDate == null ? null : endDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.report_type
     *
     * @return the value of stk_finance_cashflow.report_type
     *
     * @mbggenerated
     */
    public String getReportType() {
        return reportType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.report_type
     *
     * @param reportType the value for stk_finance_cashflow.report_type
     *
     * @mbggenerated
     */
    public void setReportType(String reportType) {
        this.reportType = reportType == null ? null : reportType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.comp_type
     *
     * @return the value of stk_finance_cashflow.comp_type
     *
     * @mbggenerated
     */
    public String getCompType() {
        return compType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.comp_type
     *
     * @param compType the value for stk_finance_cashflow.comp_type
     *
     * @mbggenerated
     */
    public void setCompType(String compType) {
        this.compType = compType == null ? null : compType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.net_profit
     *
     * @return the value of stk_finance_cashflow.net_profit
     *
     * @mbggenerated
     */
    public BigDecimal getNetProfit() {
        return netProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.net_profit
     *
     * @param netProfit the value for stk_finance_cashflow.net_profit
     *
     * @mbggenerated
     */
    public void setNetProfit(BigDecimal netProfit) {
        this.netProfit = netProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.finan_exp
     *
     * @return the value of stk_finance_cashflow.finan_exp
     *
     * @mbggenerated
     */
    public BigDecimal getFinanExp() {
        return finanExp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.finan_exp
     *
     * @param finanExp the value for stk_finance_cashflow.finan_exp
     *
     * @mbggenerated
     */
    public void setFinanExp(BigDecimal finanExp) {
        this.finanExp = finanExp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.c_fr_sale_sg
     *
     * @return the value of stk_finance_cashflow.c_fr_sale_sg
     *
     * @mbggenerated
     */
    public BigDecimal getcFrSaleSg() {
        return cFrSaleSg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.c_fr_sale_sg
     *
     * @param cFrSaleSg the value for stk_finance_cashflow.c_fr_sale_sg
     *
     * @mbggenerated
     */
    public void setcFrSaleSg(BigDecimal cFrSaleSg) {
        this.cFrSaleSg = cFrSaleSg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.recp_tax_rends
     *
     * @return the value of stk_finance_cashflow.recp_tax_rends
     *
     * @mbggenerated
     */
    public BigDecimal getRecpTaxRends() {
        return recpTaxRends;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.recp_tax_rends
     *
     * @param recpTaxRends the value for stk_finance_cashflow.recp_tax_rends
     *
     * @mbggenerated
     */
    public void setRecpTaxRends(BigDecimal recpTaxRends) {
        this.recpTaxRends = recpTaxRends;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.n_depos_incr_fi
     *
     * @return the value of stk_finance_cashflow.n_depos_incr_fi
     *
     * @mbggenerated
     */
    public BigDecimal getnDeposIncrFi() {
        return nDeposIncrFi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.n_depos_incr_fi
     *
     * @param nDeposIncrFi the value for stk_finance_cashflow.n_depos_incr_fi
     *
     * @mbggenerated
     */
    public void setnDeposIncrFi(BigDecimal nDeposIncrFi) {
        this.nDeposIncrFi = nDeposIncrFi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.n_incr_loans_cb
     *
     * @return the value of stk_finance_cashflow.n_incr_loans_cb
     *
     * @mbggenerated
     */
    public BigDecimal getnIncrLoansCb() {
        return nIncrLoansCb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.n_incr_loans_cb
     *
     * @param nIncrLoansCb the value for stk_finance_cashflow.n_incr_loans_cb
     *
     * @mbggenerated
     */
    public void setnIncrLoansCb(BigDecimal nIncrLoansCb) {
        this.nIncrLoansCb = nIncrLoansCb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.n_inc_borr_oth_fi
     *
     * @return the value of stk_finance_cashflow.n_inc_borr_oth_fi
     *
     * @mbggenerated
     */
    public BigDecimal getnIncBorrOthFi() {
        return nIncBorrOthFi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.n_inc_borr_oth_fi
     *
     * @param nIncBorrOthFi the value for stk_finance_cashflow.n_inc_borr_oth_fi
     *
     * @mbggenerated
     */
    public void setnIncBorrOthFi(BigDecimal nIncBorrOthFi) {
        this.nIncBorrOthFi = nIncBorrOthFi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.prem_fr_orig_contr
     *
     * @return the value of stk_finance_cashflow.prem_fr_orig_contr
     *
     * @mbggenerated
     */
    public BigDecimal getPremFrOrigContr() {
        return premFrOrigContr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.prem_fr_orig_contr
     *
     * @param premFrOrigContr the value for stk_finance_cashflow.prem_fr_orig_contr
     *
     * @mbggenerated
     */
    public void setPremFrOrigContr(BigDecimal premFrOrigContr) {
        this.premFrOrigContr = premFrOrigContr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.n_incr_insured_dep
     *
     * @return the value of stk_finance_cashflow.n_incr_insured_dep
     *
     * @mbggenerated
     */
    public BigDecimal getnIncrInsuredDep() {
        return nIncrInsuredDep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.n_incr_insured_dep
     *
     * @param nIncrInsuredDep the value for stk_finance_cashflow.n_incr_insured_dep
     *
     * @mbggenerated
     */
    public void setnIncrInsuredDep(BigDecimal nIncrInsuredDep) {
        this.nIncrInsuredDep = nIncrInsuredDep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.n_reinsur_prem
     *
     * @return the value of stk_finance_cashflow.n_reinsur_prem
     *
     * @mbggenerated
     */
    public BigDecimal getnReinsurPrem() {
        return nReinsurPrem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.n_reinsur_prem
     *
     * @param nReinsurPrem the value for stk_finance_cashflow.n_reinsur_prem
     *
     * @mbggenerated
     */
    public void setnReinsurPrem(BigDecimal nReinsurPrem) {
        this.nReinsurPrem = nReinsurPrem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.n_incr_disp_tfa
     *
     * @return the value of stk_finance_cashflow.n_incr_disp_tfa
     *
     * @mbggenerated
     */
    public BigDecimal getnIncrDispTfa() {
        return nIncrDispTfa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.n_incr_disp_tfa
     *
     * @param nIncrDispTfa the value for stk_finance_cashflow.n_incr_disp_tfa
     *
     * @mbggenerated
     */
    public void setnIncrDispTfa(BigDecimal nIncrDispTfa) {
        this.nIncrDispTfa = nIncrDispTfa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.ifc_cash_incr
     *
     * @return the value of stk_finance_cashflow.ifc_cash_incr
     *
     * @mbggenerated
     */
    public BigDecimal getIfcCashIncr() {
        return ifcCashIncr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.ifc_cash_incr
     *
     * @param ifcCashIncr the value for stk_finance_cashflow.ifc_cash_incr
     *
     * @mbggenerated
     */
    public void setIfcCashIncr(BigDecimal ifcCashIncr) {
        this.ifcCashIncr = ifcCashIncr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.n_incr_disp_faas
     *
     * @return the value of stk_finance_cashflow.n_incr_disp_faas
     *
     * @mbggenerated
     */
    public BigDecimal getnIncrDispFaas() {
        return nIncrDispFaas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.n_incr_disp_faas
     *
     * @param nIncrDispFaas the value for stk_finance_cashflow.n_incr_disp_faas
     *
     * @mbggenerated
     */
    public void setnIncrDispFaas(BigDecimal nIncrDispFaas) {
        this.nIncrDispFaas = nIncrDispFaas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.n_incr_loans_oth_bank
     *
     * @return the value of stk_finance_cashflow.n_incr_loans_oth_bank
     *
     * @mbggenerated
     */
    public BigDecimal getnIncrLoansOthBank() {
        return nIncrLoansOthBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.n_incr_loans_oth_bank
     *
     * @param nIncrLoansOthBank the value for stk_finance_cashflow.n_incr_loans_oth_bank
     *
     * @mbggenerated
     */
    public void setnIncrLoansOthBank(BigDecimal nIncrLoansOthBank) {
        this.nIncrLoansOthBank = nIncrLoansOthBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.n_cap_incr_repur
     *
     * @return the value of stk_finance_cashflow.n_cap_incr_repur
     *
     * @mbggenerated
     */
    public BigDecimal getnCapIncrRepur() {
        return nCapIncrRepur;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.n_cap_incr_repur
     *
     * @param nCapIncrRepur the value for stk_finance_cashflow.n_cap_incr_repur
     *
     * @mbggenerated
     */
    public void setnCapIncrRepur(BigDecimal nCapIncrRepur) {
        this.nCapIncrRepur = nCapIncrRepur;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.c_fr_oth_operate_a
     *
     * @return the value of stk_finance_cashflow.c_fr_oth_operate_a
     *
     * @mbggenerated
     */
    public BigDecimal getcFrOthOperateA() {
        return cFrOthOperateA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.c_fr_oth_operate_a
     *
     * @param cFrOthOperateA the value for stk_finance_cashflow.c_fr_oth_operate_a
     *
     * @mbggenerated
     */
    public void setcFrOthOperateA(BigDecimal cFrOthOperateA) {
        this.cFrOthOperateA = cFrOthOperateA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.c_inf_fr_operate_a
     *
     * @return the value of stk_finance_cashflow.c_inf_fr_operate_a
     *
     * @mbggenerated
     */
    public BigDecimal getcInfFrOperateA() {
        return cInfFrOperateA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.c_inf_fr_operate_a
     *
     * @param cInfFrOperateA the value for stk_finance_cashflow.c_inf_fr_operate_a
     *
     * @mbggenerated
     */
    public void setcInfFrOperateA(BigDecimal cInfFrOperateA) {
        this.cInfFrOperateA = cInfFrOperateA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.c_paid_goods_s
     *
     * @return the value of stk_finance_cashflow.c_paid_goods_s
     *
     * @mbggenerated
     */
    public BigDecimal getcPaidGoodsS() {
        return cPaidGoodsS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.c_paid_goods_s
     *
     * @param cPaidGoodsS the value for stk_finance_cashflow.c_paid_goods_s
     *
     * @mbggenerated
     */
    public void setcPaidGoodsS(BigDecimal cPaidGoodsS) {
        this.cPaidGoodsS = cPaidGoodsS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.c_paid_to_for_empl
     *
     * @return the value of stk_finance_cashflow.c_paid_to_for_empl
     *
     * @mbggenerated
     */
    public BigDecimal getcPaidToForEmpl() {
        return cPaidToForEmpl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.c_paid_to_for_empl
     *
     * @param cPaidToForEmpl the value for stk_finance_cashflow.c_paid_to_for_empl
     *
     * @mbggenerated
     */
    public void setcPaidToForEmpl(BigDecimal cPaidToForEmpl) {
        this.cPaidToForEmpl = cPaidToForEmpl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.c_paid_for_taxes
     *
     * @return the value of stk_finance_cashflow.c_paid_for_taxes
     *
     * @mbggenerated
     */
    public BigDecimal getcPaidForTaxes() {
        return cPaidForTaxes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.c_paid_for_taxes
     *
     * @param cPaidForTaxes the value for stk_finance_cashflow.c_paid_for_taxes
     *
     * @mbggenerated
     */
    public void setcPaidForTaxes(BigDecimal cPaidForTaxes) {
        this.cPaidForTaxes = cPaidForTaxes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.n_incr_clt_loan_adv
     *
     * @return the value of stk_finance_cashflow.n_incr_clt_loan_adv
     *
     * @mbggenerated
     */
    public BigDecimal getnIncrCltLoanAdv() {
        return nIncrCltLoanAdv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.n_incr_clt_loan_adv
     *
     * @param nIncrCltLoanAdv the value for stk_finance_cashflow.n_incr_clt_loan_adv
     *
     * @mbggenerated
     */
    public void setnIncrCltLoanAdv(BigDecimal nIncrCltLoanAdv) {
        this.nIncrCltLoanAdv = nIncrCltLoanAdv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.n_incr_dep_cbob
     *
     * @return the value of stk_finance_cashflow.n_incr_dep_cbob
     *
     * @mbggenerated
     */
    public BigDecimal getnIncrDepCbob() {
        return nIncrDepCbob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.n_incr_dep_cbob
     *
     * @param nIncrDepCbob the value for stk_finance_cashflow.n_incr_dep_cbob
     *
     * @mbggenerated
     */
    public void setnIncrDepCbob(BigDecimal nIncrDepCbob) {
        this.nIncrDepCbob = nIncrDepCbob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.c_pay_claims_orig_inco
     *
     * @return the value of stk_finance_cashflow.c_pay_claims_orig_inco
     *
     * @mbggenerated
     */
    public BigDecimal getcPayClaimsOrigInco() {
        return cPayClaimsOrigInco;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.c_pay_claims_orig_inco
     *
     * @param cPayClaimsOrigInco the value for stk_finance_cashflow.c_pay_claims_orig_inco
     *
     * @mbggenerated
     */
    public void setcPayClaimsOrigInco(BigDecimal cPayClaimsOrigInco) {
        this.cPayClaimsOrigInco = cPayClaimsOrigInco;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.pay_handling_chrg
     *
     * @return the value of stk_finance_cashflow.pay_handling_chrg
     *
     * @mbggenerated
     */
    public BigDecimal getPayHandlingChrg() {
        return payHandlingChrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.pay_handling_chrg
     *
     * @param payHandlingChrg the value for stk_finance_cashflow.pay_handling_chrg
     *
     * @mbggenerated
     */
    public void setPayHandlingChrg(BigDecimal payHandlingChrg) {
        this.payHandlingChrg = payHandlingChrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.pay_comm_insur_plcy
     *
     * @return the value of stk_finance_cashflow.pay_comm_insur_plcy
     *
     * @mbggenerated
     */
    public BigDecimal getPayCommInsurPlcy() {
        return payCommInsurPlcy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.pay_comm_insur_plcy
     *
     * @param payCommInsurPlcy the value for stk_finance_cashflow.pay_comm_insur_plcy
     *
     * @mbggenerated
     */
    public void setPayCommInsurPlcy(BigDecimal payCommInsurPlcy) {
        this.payCommInsurPlcy = payCommInsurPlcy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.oth_cash_pay_oper_act
     *
     * @return the value of stk_finance_cashflow.oth_cash_pay_oper_act
     *
     * @mbggenerated
     */
    public BigDecimal getOthCashPayOperAct() {
        return othCashPayOperAct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.oth_cash_pay_oper_act
     *
     * @param othCashPayOperAct the value for stk_finance_cashflow.oth_cash_pay_oper_act
     *
     * @mbggenerated
     */
    public void setOthCashPayOperAct(BigDecimal othCashPayOperAct) {
        this.othCashPayOperAct = othCashPayOperAct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.st_cash_out_act
     *
     * @return the value of stk_finance_cashflow.st_cash_out_act
     *
     * @mbggenerated
     */
    public BigDecimal getStCashOutAct() {
        return stCashOutAct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.st_cash_out_act
     *
     * @param stCashOutAct the value for stk_finance_cashflow.st_cash_out_act
     *
     * @mbggenerated
     */
    public void setStCashOutAct(BigDecimal stCashOutAct) {
        this.stCashOutAct = stCashOutAct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.n_cashflow_act
     *
     * @return the value of stk_finance_cashflow.n_cashflow_act
     *
     * @mbggenerated
     */
    public BigDecimal getnCashflowAct() {
        return nCashflowAct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.n_cashflow_act
     *
     * @param nCashflowAct the value for stk_finance_cashflow.n_cashflow_act
     *
     * @mbggenerated
     */
    public void setnCashflowAct(BigDecimal nCashflowAct) {
        this.nCashflowAct = nCashflowAct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.oth_recp_ral_inv_act
     *
     * @return the value of stk_finance_cashflow.oth_recp_ral_inv_act
     *
     * @mbggenerated
     */
    public BigDecimal getOthRecpRalInvAct() {
        return othRecpRalInvAct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.oth_recp_ral_inv_act
     *
     * @param othRecpRalInvAct the value for stk_finance_cashflow.oth_recp_ral_inv_act
     *
     * @mbggenerated
     */
    public void setOthRecpRalInvAct(BigDecimal othRecpRalInvAct) {
        this.othRecpRalInvAct = othRecpRalInvAct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.c_disp_withdrwl_invest
     *
     * @return the value of stk_finance_cashflow.c_disp_withdrwl_invest
     *
     * @mbggenerated
     */
    public BigDecimal getcDispWithdrwlInvest() {
        return cDispWithdrwlInvest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.c_disp_withdrwl_invest
     *
     * @param cDispWithdrwlInvest the value for stk_finance_cashflow.c_disp_withdrwl_invest
     *
     * @mbggenerated
     */
    public void setcDispWithdrwlInvest(BigDecimal cDispWithdrwlInvest) {
        this.cDispWithdrwlInvest = cDispWithdrwlInvest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.c_recp_return_invest
     *
     * @return the value of stk_finance_cashflow.c_recp_return_invest
     *
     * @mbggenerated
     */
    public BigDecimal getcRecpReturnInvest() {
        return cRecpReturnInvest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.c_recp_return_invest
     *
     * @param cRecpReturnInvest the value for stk_finance_cashflow.c_recp_return_invest
     *
     * @mbggenerated
     */
    public void setcRecpReturnInvest(BigDecimal cRecpReturnInvest) {
        this.cRecpReturnInvest = cRecpReturnInvest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.n_recp_disp_fiolta
     *
     * @return the value of stk_finance_cashflow.n_recp_disp_fiolta
     *
     * @mbggenerated
     */
    public BigDecimal getnRecpDispFiolta() {
        return nRecpDispFiolta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.n_recp_disp_fiolta
     *
     * @param nRecpDispFiolta the value for stk_finance_cashflow.n_recp_disp_fiolta
     *
     * @mbggenerated
     */
    public void setnRecpDispFiolta(BigDecimal nRecpDispFiolta) {
        this.nRecpDispFiolta = nRecpDispFiolta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.n_recp_disp_sobu
     *
     * @return the value of stk_finance_cashflow.n_recp_disp_sobu
     *
     * @mbggenerated
     */
    public BigDecimal getnRecpDispSobu() {
        return nRecpDispSobu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.n_recp_disp_sobu
     *
     * @param nRecpDispSobu the value for stk_finance_cashflow.n_recp_disp_sobu
     *
     * @mbggenerated
     */
    public void setnRecpDispSobu(BigDecimal nRecpDispSobu) {
        this.nRecpDispSobu = nRecpDispSobu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.stot_inflows_inv_act
     *
     * @return the value of stk_finance_cashflow.stot_inflows_inv_act
     *
     * @mbggenerated
     */
    public BigDecimal getStotInflowsInvAct() {
        return stotInflowsInvAct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.stot_inflows_inv_act
     *
     * @param stotInflowsInvAct the value for stk_finance_cashflow.stot_inflows_inv_act
     *
     * @mbggenerated
     */
    public void setStotInflowsInvAct(BigDecimal stotInflowsInvAct) {
        this.stotInflowsInvAct = stotInflowsInvAct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.c_pay_acq_const_fiolta
     *
     * @return the value of stk_finance_cashflow.c_pay_acq_const_fiolta
     *
     * @mbggenerated
     */
    public BigDecimal getcPayAcqConstFiolta() {
        return cPayAcqConstFiolta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.c_pay_acq_const_fiolta
     *
     * @param cPayAcqConstFiolta the value for stk_finance_cashflow.c_pay_acq_const_fiolta
     *
     * @mbggenerated
     */
    public void setcPayAcqConstFiolta(BigDecimal cPayAcqConstFiolta) {
        this.cPayAcqConstFiolta = cPayAcqConstFiolta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.c_paid_invest
     *
     * @return the value of stk_finance_cashflow.c_paid_invest
     *
     * @mbggenerated
     */
    public BigDecimal getcPaidInvest() {
        return cPaidInvest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.c_paid_invest
     *
     * @param cPaidInvest the value for stk_finance_cashflow.c_paid_invest
     *
     * @mbggenerated
     */
    public void setcPaidInvest(BigDecimal cPaidInvest) {
        this.cPaidInvest = cPaidInvest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.n_disp_subs_oth_biz
     *
     * @return the value of stk_finance_cashflow.n_disp_subs_oth_biz
     *
     * @mbggenerated
     */
    public BigDecimal getnDispSubsOthBiz() {
        return nDispSubsOthBiz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.n_disp_subs_oth_biz
     *
     * @param nDispSubsOthBiz the value for stk_finance_cashflow.n_disp_subs_oth_biz
     *
     * @mbggenerated
     */
    public void setnDispSubsOthBiz(BigDecimal nDispSubsOthBiz) {
        this.nDispSubsOthBiz = nDispSubsOthBiz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.oth_pay_ral_inv_act
     *
     * @return the value of stk_finance_cashflow.oth_pay_ral_inv_act
     *
     * @mbggenerated
     */
    public BigDecimal getOthPayRalInvAct() {
        return othPayRalInvAct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.oth_pay_ral_inv_act
     *
     * @param othPayRalInvAct the value for stk_finance_cashflow.oth_pay_ral_inv_act
     *
     * @mbggenerated
     */
    public void setOthPayRalInvAct(BigDecimal othPayRalInvAct) {
        this.othPayRalInvAct = othPayRalInvAct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.n_incr_pledge_loan
     *
     * @return the value of stk_finance_cashflow.n_incr_pledge_loan
     *
     * @mbggenerated
     */
    public BigDecimal getnIncrPledgeLoan() {
        return nIncrPledgeLoan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.n_incr_pledge_loan
     *
     * @param nIncrPledgeLoan the value for stk_finance_cashflow.n_incr_pledge_loan
     *
     * @mbggenerated
     */
    public void setnIncrPledgeLoan(BigDecimal nIncrPledgeLoan) {
        this.nIncrPledgeLoan = nIncrPledgeLoan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.stot_out_inv_act
     *
     * @return the value of stk_finance_cashflow.stot_out_inv_act
     *
     * @mbggenerated
     */
    public BigDecimal getStotOutInvAct() {
        return stotOutInvAct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.stot_out_inv_act
     *
     * @param stotOutInvAct the value for stk_finance_cashflow.stot_out_inv_act
     *
     * @mbggenerated
     */
    public void setStotOutInvAct(BigDecimal stotOutInvAct) {
        this.stotOutInvAct = stotOutInvAct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.n_cashflow_inv_act
     *
     * @return the value of stk_finance_cashflow.n_cashflow_inv_act
     *
     * @mbggenerated
     */
    public BigDecimal getnCashflowInvAct() {
        return nCashflowInvAct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.n_cashflow_inv_act
     *
     * @param nCashflowInvAct the value for stk_finance_cashflow.n_cashflow_inv_act
     *
     * @mbggenerated
     */
    public void setnCashflowInvAct(BigDecimal nCashflowInvAct) {
        this.nCashflowInvAct = nCashflowInvAct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.c_recp_borrow
     *
     * @return the value of stk_finance_cashflow.c_recp_borrow
     *
     * @mbggenerated
     */
    public BigDecimal getcRecpBorrow() {
        return cRecpBorrow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.c_recp_borrow
     *
     * @param cRecpBorrow the value for stk_finance_cashflow.c_recp_borrow
     *
     * @mbggenerated
     */
    public void setcRecpBorrow(BigDecimal cRecpBorrow) {
        this.cRecpBorrow = cRecpBorrow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.proc_issue_bonds
     *
     * @return the value of stk_finance_cashflow.proc_issue_bonds
     *
     * @mbggenerated
     */
    public BigDecimal getProcIssueBonds() {
        return procIssueBonds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.proc_issue_bonds
     *
     * @param procIssueBonds the value for stk_finance_cashflow.proc_issue_bonds
     *
     * @mbggenerated
     */
    public void setProcIssueBonds(BigDecimal procIssueBonds) {
        this.procIssueBonds = procIssueBonds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.oth_cash_recp_ral_fnc_act
     *
     * @return the value of stk_finance_cashflow.oth_cash_recp_ral_fnc_act
     *
     * @mbggenerated
     */
    public BigDecimal getOthCashRecpRalFncAct() {
        return othCashRecpRalFncAct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.oth_cash_recp_ral_fnc_act
     *
     * @param othCashRecpRalFncAct the value for stk_finance_cashflow.oth_cash_recp_ral_fnc_act
     *
     * @mbggenerated
     */
    public void setOthCashRecpRalFncAct(BigDecimal othCashRecpRalFncAct) {
        this.othCashRecpRalFncAct = othCashRecpRalFncAct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.stot_cash_in_fnc_act
     *
     * @return the value of stk_finance_cashflow.stot_cash_in_fnc_act
     *
     * @mbggenerated
     */
    public BigDecimal getStotCashInFncAct() {
        return stotCashInFncAct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.stot_cash_in_fnc_act
     *
     * @param stotCashInFncAct the value for stk_finance_cashflow.stot_cash_in_fnc_act
     *
     * @mbggenerated
     */
    public void setStotCashInFncAct(BigDecimal stotCashInFncAct) {
        this.stotCashInFncAct = stotCashInFncAct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.free_cashflow
     *
     * @return the value of stk_finance_cashflow.free_cashflow
     *
     * @mbggenerated
     */
    public BigDecimal getFreeCashflow() {
        return freeCashflow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.free_cashflow
     *
     * @param freeCashflow the value for stk_finance_cashflow.free_cashflow
     *
     * @mbggenerated
     */
    public void setFreeCashflow(BigDecimal freeCashflow) {
        this.freeCashflow = freeCashflow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.c_prepay_amt_borr
     *
     * @return the value of stk_finance_cashflow.c_prepay_amt_borr
     *
     * @mbggenerated
     */
    public BigDecimal getcPrepayAmtBorr() {
        return cPrepayAmtBorr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.c_prepay_amt_borr
     *
     * @param cPrepayAmtBorr the value for stk_finance_cashflow.c_prepay_amt_borr
     *
     * @mbggenerated
     */
    public void setcPrepayAmtBorr(BigDecimal cPrepayAmtBorr) {
        this.cPrepayAmtBorr = cPrepayAmtBorr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.c_pay_dist_dpcp_int_exp
     *
     * @return the value of stk_finance_cashflow.c_pay_dist_dpcp_int_exp
     *
     * @mbggenerated
     */
    public BigDecimal getcPayDistDpcpIntExp() {
        return cPayDistDpcpIntExp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.c_pay_dist_dpcp_int_exp
     *
     * @param cPayDistDpcpIntExp the value for stk_finance_cashflow.c_pay_dist_dpcp_int_exp
     *
     * @mbggenerated
     */
    public void setcPayDistDpcpIntExp(BigDecimal cPayDistDpcpIntExp) {
        this.cPayDistDpcpIntExp = cPayDistDpcpIntExp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.incl_dvd_profit_paid_sc_ms
     *
     * @return the value of stk_finance_cashflow.incl_dvd_profit_paid_sc_ms
     *
     * @mbggenerated
     */
    public BigDecimal getInclDvdProfitPaidScMs() {
        return inclDvdProfitPaidScMs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.incl_dvd_profit_paid_sc_ms
     *
     * @param inclDvdProfitPaidScMs the value for stk_finance_cashflow.incl_dvd_profit_paid_sc_ms
     *
     * @mbggenerated
     */
    public void setInclDvdProfitPaidScMs(BigDecimal inclDvdProfitPaidScMs) {
        this.inclDvdProfitPaidScMs = inclDvdProfitPaidScMs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.oth_cashpay_ral_fnc_act
     *
     * @return the value of stk_finance_cashflow.oth_cashpay_ral_fnc_act
     *
     * @mbggenerated
     */
    public BigDecimal getOthCashpayRalFncAct() {
        return othCashpayRalFncAct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.oth_cashpay_ral_fnc_act
     *
     * @param othCashpayRalFncAct the value for stk_finance_cashflow.oth_cashpay_ral_fnc_act
     *
     * @mbggenerated
     */
    public void setOthCashpayRalFncAct(BigDecimal othCashpayRalFncAct) {
        this.othCashpayRalFncAct = othCashpayRalFncAct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.stot_cashout_fnc_act
     *
     * @return the value of stk_finance_cashflow.stot_cashout_fnc_act
     *
     * @mbggenerated
     */
    public BigDecimal getStotCashoutFncAct() {
        return stotCashoutFncAct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.stot_cashout_fnc_act
     *
     * @param stotCashoutFncAct the value for stk_finance_cashflow.stot_cashout_fnc_act
     *
     * @mbggenerated
     */
    public void setStotCashoutFncAct(BigDecimal stotCashoutFncAct) {
        this.stotCashoutFncAct = stotCashoutFncAct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.n_cash_flows_fnc_act
     *
     * @return the value of stk_finance_cashflow.n_cash_flows_fnc_act
     *
     * @mbggenerated
     */
    public BigDecimal getnCashFlowsFncAct() {
        return nCashFlowsFncAct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.n_cash_flows_fnc_act
     *
     * @param nCashFlowsFncAct the value for stk_finance_cashflow.n_cash_flows_fnc_act
     *
     * @mbggenerated
     */
    public void setnCashFlowsFncAct(BigDecimal nCashFlowsFncAct) {
        this.nCashFlowsFncAct = nCashFlowsFncAct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.eff_fx_flu_cash
     *
     * @return the value of stk_finance_cashflow.eff_fx_flu_cash
     *
     * @mbggenerated
     */
    public BigDecimal getEffFxFluCash() {
        return effFxFluCash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.eff_fx_flu_cash
     *
     * @param effFxFluCash the value for stk_finance_cashflow.eff_fx_flu_cash
     *
     * @mbggenerated
     */
    public void setEffFxFluCash(BigDecimal effFxFluCash) {
        this.effFxFluCash = effFxFluCash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.n_incr_cash_cash_equ
     *
     * @return the value of stk_finance_cashflow.n_incr_cash_cash_equ
     *
     * @mbggenerated
     */
    public BigDecimal getnIncrCashCashEqu() {
        return nIncrCashCashEqu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.n_incr_cash_cash_equ
     *
     * @param nIncrCashCashEqu the value for stk_finance_cashflow.n_incr_cash_cash_equ
     *
     * @mbggenerated
     */
    public void setnIncrCashCashEqu(BigDecimal nIncrCashCashEqu) {
        this.nIncrCashCashEqu = nIncrCashCashEqu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.c_cash_equ_beg_period
     *
     * @return the value of stk_finance_cashflow.c_cash_equ_beg_period
     *
     * @mbggenerated
     */
    public BigDecimal getcCashEquBegPeriod() {
        return cCashEquBegPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.c_cash_equ_beg_period
     *
     * @param cCashEquBegPeriod the value for stk_finance_cashflow.c_cash_equ_beg_period
     *
     * @mbggenerated
     */
    public void setcCashEquBegPeriod(BigDecimal cCashEquBegPeriod) {
        this.cCashEquBegPeriod = cCashEquBegPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.c_cash_equ_end_period
     *
     * @return the value of stk_finance_cashflow.c_cash_equ_end_period
     *
     * @mbggenerated
     */
    public BigDecimal getcCashEquEndPeriod() {
        return cCashEquEndPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.c_cash_equ_end_period
     *
     * @param cCashEquEndPeriod the value for stk_finance_cashflow.c_cash_equ_end_period
     *
     * @mbggenerated
     */
    public void setcCashEquEndPeriod(BigDecimal cCashEquEndPeriod) {
        this.cCashEquEndPeriod = cCashEquEndPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.c_recp_cap_contrib
     *
     * @return the value of stk_finance_cashflow.c_recp_cap_contrib
     *
     * @mbggenerated
     */
    public BigDecimal getcRecpCapContrib() {
        return cRecpCapContrib;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.c_recp_cap_contrib
     *
     * @param cRecpCapContrib the value for stk_finance_cashflow.c_recp_cap_contrib
     *
     * @mbggenerated
     */
    public void setcRecpCapContrib(BigDecimal cRecpCapContrib) {
        this.cRecpCapContrib = cRecpCapContrib;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.incl_cash_rec_saims
     *
     * @return the value of stk_finance_cashflow.incl_cash_rec_saims
     *
     * @mbggenerated
     */
    public BigDecimal getInclCashRecSaims() {
        return inclCashRecSaims;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.incl_cash_rec_saims
     *
     * @param inclCashRecSaims the value for stk_finance_cashflow.incl_cash_rec_saims
     *
     * @mbggenerated
     */
    public void setInclCashRecSaims(BigDecimal inclCashRecSaims) {
        this.inclCashRecSaims = inclCashRecSaims;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.uncon_invest_loss
     *
     * @return the value of stk_finance_cashflow.uncon_invest_loss
     *
     * @mbggenerated
     */
    public BigDecimal getUnconInvestLoss() {
        return unconInvestLoss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.uncon_invest_loss
     *
     * @param unconInvestLoss the value for stk_finance_cashflow.uncon_invest_loss
     *
     * @mbggenerated
     */
    public void setUnconInvestLoss(BigDecimal unconInvestLoss) {
        this.unconInvestLoss = unconInvestLoss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.prov_depr_assets
     *
     * @return the value of stk_finance_cashflow.prov_depr_assets
     *
     * @mbggenerated
     */
    public BigDecimal getProvDeprAssets() {
        return provDeprAssets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.prov_depr_assets
     *
     * @param provDeprAssets the value for stk_finance_cashflow.prov_depr_assets
     *
     * @mbggenerated
     */
    public void setProvDeprAssets(BigDecimal provDeprAssets) {
        this.provDeprAssets = provDeprAssets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.depr_fa_coga_dpba
     *
     * @return the value of stk_finance_cashflow.depr_fa_coga_dpba
     *
     * @mbggenerated
     */
    public BigDecimal getDeprFaCogaDpba() {
        return deprFaCogaDpba;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.depr_fa_coga_dpba
     *
     * @param deprFaCogaDpba the value for stk_finance_cashflow.depr_fa_coga_dpba
     *
     * @mbggenerated
     */
    public void setDeprFaCogaDpba(BigDecimal deprFaCogaDpba) {
        this.deprFaCogaDpba = deprFaCogaDpba;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.amort_intang_assets
     *
     * @return the value of stk_finance_cashflow.amort_intang_assets
     *
     * @mbggenerated
     */
    public BigDecimal getAmortIntangAssets() {
        return amortIntangAssets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.amort_intang_assets
     *
     * @param amortIntangAssets the value for stk_finance_cashflow.amort_intang_assets
     *
     * @mbggenerated
     */
    public void setAmortIntangAssets(BigDecimal amortIntangAssets) {
        this.amortIntangAssets = amortIntangAssets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.lt_amort_deferred_exp
     *
     * @return the value of stk_finance_cashflow.lt_amort_deferred_exp
     *
     * @mbggenerated
     */
    public BigDecimal getLtAmortDeferredExp() {
        return ltAmortDeferredExp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.lt_amort_deferred_exp
     *
     * @param ltAmortDeferredExp the value for stk_finance_cashflow.lt_amort_deferred_exp
     *
     * @mbggenerated
     */
    public void setLtAmortDeferredExp(BigDecimal ltAmortDeferredExp) {
        this.ltAmortDeferredExp = ltAmortDeferredExp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.decr_deferred_exp
     *
     * @return the value of stk_finance_cashflow.decr_deferred_exp
     *
     * @mbggenerated
     */
    public BigDecimal getDecrDeferredExp() {
        return decrDeferredExp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.decr_deferred_exp
     *
     * @param decrDeferredExp the value for stk_finance_cashflow.decr_deferred_exp
     *
     * @mbggenerated
     */
    public void setDecrDeferredExp(BigDecimal decrDeferredExp) {
        this.decrDeferredExp = decrDeferredExp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.incr_acc_exp
     *
     * @return the value of stk_finance_cashflow.incr_acc_exp
     *
     * @mbggenerated
     */
    public BigDecimal getIncrAccExp() {
        return incrAccExp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.incr_acc_exp
     *
     * @param incrAccExp the value for stk_finance_cashflow.incr_acc_exp
     *
     * @mbggenerated
     */
    public void setIncrAccExp(BigDecimal incrAccExp) {
        this.incrAccExp = incrAccExp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.loss_disp_fiolta
     *
     * @return the value of stk_finance_cashflow.loss_disp_fiolta
     *
     * @mbggenerated
     */
    public BigDecimal getLossDispFiolta() {
        return lossDispFiolta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.loss_disp_fiolta
     *
     * @param lossDispFiolta the value for stk_finance_cashflow.loss_disp_fiolta
     *
     * @mbggenerated
     */
    public void setLossDispFiolta(BigDecimal lossDispFiolta) {
        this.lossDispFiolta = lossDispFiolta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.loss_scr_fa
     *
     * @return the value of stk_finance_cashflow.loss_scr_fa
     *
     * @mbggenerated
     */
    public BigDecimal getLossScrFa() {
        return lossScrFa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.loss_scr_fa
     *
     * @param lossScrFa the value for stk_finance_cashflow.loss_scr_fa
     *
     * @mbggenerated
     */
    public void setLossScrFa(BigDecimal lossScrFa) {
        this.lossScrFa = lossScrFa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.loss_fv_chg
     *
     * @return the value of stk_finance_cashflow.loss_fv_chg
     *
     * @mbggenerated
     */
    public BigDecimal getLossFvChg() {
        return lossFvChg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.loss_fv_chg
     *
     * @param lossFvChg the value for stk_finance_cashflow.loss_fv_chg
     *
     * @mbggenerated
     */
    public void setLossFvChg(BigDecimal lossFvChg) {
        this.lossFvChg = lossFvChg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.invest_loss
     *
     * @return the value of stk_finance_cashflow.invest_loss
     *
     * @mbggenerated
     */
    public BigDecimal getInvestLoss() {
        return investLoss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.invest_loss
     *
     * @param investLoss the value for stk_finance_cashflow.invest_loss
     *
     * @mbggenerated
     */
    public void setInvestLoss(BigDecimal investLoss) {
        this.investLoss = investLoss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.decr_def_inc_tax_assets
     *
     * @return the value of stk_finance_cashflow.decr_def_inc_tax_assets
     *
     * @mbggenerated
     */
    public BigDecimal getDecrDefIncTaxAssets() {
        return decrDefIncTaxAssets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.decr_def_inc_tax_assets
     *
     * @param decrDefIncTaxAssets the value for stk_finance_cashflow.decr_def_inc_tax_assets
     *
     * @mbggenerated
     */
    public void setDecrDefIncTaxAssets(BigDecimal decrDefIncTaxAssets) {
        this.decrDefIncTaxAssets = decrDefIncTaxAssets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.incr_def_inc_tax_liab
     *
     * @return the value of stk_finance_cashflow.incr_def_inc_tax_liab
     *
     * @mbggenerated
     */
    public BigDecimal getIncrDefIncTaxLiab() {
        return incrDefIncTaxLiab;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.incr_def_inc_tax_liab
     *
     * @param incrDefIncTaxLiab the value for stk_finance_cashflow.incr_def_inc_tax_liab
     *
     * @mbggenerated
     */
    public void setIncrDefIncTaxLiab(BigDecimal incrDefIncTaxLiab) {
        this.incrDefIncTaxLiab = incrDefIncTaxLiab;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.decr_inventories
     *
     * @return the value of stk_finance_cashflow.decr_inventories
     *
     * @mbggenerated
     */
    public BigDecimal getDecrInventories() {
        return decrInventories;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.decr_inventories
     *
     * @param decrInventories the value for stk_finance_cashflow.decr_inventories
     *
     * @mbggenerated
     */
    public void setDecrInventories(BigDecimal decrInventories) {
        this.decrInventories = decrInventories;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.decr_oper_payable
     *
     * @return the value of stk_finance_cashflow.decr_oper_payable
     *
     * @mbggenerated
     */
    public BigDecimal getDecrOperPayable() {
        return decrOperPayable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.decr_oper_payable
     *
     * @param decrOperPayable the value for stk_finance_cashflow.decr_oper_payable
     *
     * @mbggenerated
     */
    public void setDecrOperPayable(BigDecimal decrOperPayable) {
        this.decrOperPayable = decrOperPayable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.incr_oper_payable
     *
     * @return the value of stk_finance_cashflow.incr_oper_payable
     *
     * @mbggenerated
     */
    public BigDecimal getIncrOperPayable() {
        return incrOperPayable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.incr_oper_payable
     *
     * @param incrOperPayable the value for stk_finance_cashflow.incr_oper_payable
     *
     * @mbggenerated
     */
    public void setIncrOperPayable(BigDecimal incrOperPayable) {
        this.incrOperPayable = incrOperPayable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.others
     *
     * @return the value of stk_finance_cashflow.others
     *
     * @mbggenerated
     */
    public BigDecimal getOthers() {
        return others;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.others
     *
     * @param others the value for stk_finance_cashflow.others
     *
     * @mbggenerated
     */
    public void setOthers(BigDecimal others) {
        this.others = others;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.im_net_cashflow_oper_act
     *
     * @return the value of stk_finance_cashflow.im_net_cashflow_oper_act
     *
     * @mbggenerated
     */
    public BigDecimal getImNetCashflowOperAct() {
        return imNetCashflowOperAct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.im_net_cashflow_oper_act
     *
     * @param imNetCashflowOperAct the value for stk_finance_cashflow.im_net_cashflow_oper_act
     *
     * @mbggenerated
     */
    public void setImNetCashflowOperAct(BigDecimal imNetCashflowOperAct) {
        this.imNetCashflowOperAct = imNetCashflowOperAct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.conv_debt_into_cap
     *
     * @return the value of stk_finance_cashflow.conv_debt_into_cap
     *
     * @mbggenerated
     */
    public BigDecimal getConvDebtIntoCap() {
        return convDebtIntoCap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.conv_debt_into_cap
     *
     * @param convDebtIntoCap the value for stk_finance_cashflow.conv_debt_into_cap
     *
     * @mbggenerated
     */
    public void setConvDebtIntoCap(BigDecimal convDebtIntoCap) {
        this.convDebtIntoCap = convDebtIntoCap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.conv_copbonds_due_within_1y
     *
     * @return the value of stk_finance_cashflow.conv_copbonds_due_within_1y
     *
     * @mbggenerated
     */
    public BigDecimal getConvCopbondsDueWithin1y() {
        return convCopbondsDueWithin1y;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.conv_copbonds_due_within_1y
     *
     * @param convCopbondsDueWithin1y the value for stk_finance_cashflow.conv_copbonds_due_within_1y
     *
     * @mbggenerated
     */
    public void setConvCopbondsDueWithin1y(BigDecimal convCopbondsDueWithin1y) {
        this.convCopbondsDueWithin1y = convCopbondsDueWithin1y;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.fa_fnc_leases
     *
     * @return the value of stk_finance_cashflow.fa_fnc_leases
     *
     * @mbggenerated
     */
    public BigDecimal getFaFncLeases() {
        return faFncLeases;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.fa_fnc_leases
     *
     * @param faFncLeases the value for stk_finance_cashflow.fa_fnc_leases
     *
     * @mbggenerated
     */
    public void setFaFncLeases(BigDecimal faFncLeases) {
        this.faFncLeases = faFncLeases;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.end_bal_cash
     *
     * @return the value of stk_finance_cashflow.end_bal_cash
     *
     * @mbggenerated
     */
    public BigDecimal getEndBalCash() {
        return endBalCash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.end_bal_cash
     *
     * @param endBalCash the value for stk_finance_cashflow.end_bal_cash
     *
     * @mbggenerated
     */
    public void setEndBalCash(BigDecimal endBalCash) {
        this.endBalCash = endBalCash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.beg_bal_cash
     *
     * @return the value of stk_finance_cashflow.beg_bal_cash
     *
     * @mbggenerated
     */
    public BigDecimal getBegBalCash() {
        return begBalCash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.beg_bal_cash
     *
     * @param begBalCash the value for stk_finance_cashflow.beg_bal_cash
     *
     * @mbggenerated
     */
    public void setBegBalCash(BigDecimal begBalCash) {
        this.begBalCash = begBalCash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.end_bal_cash_equ
     *
     * @return the value of stk_finance_cashflow.end_bal_cash_equ
     *
     * @mbggenerated
     */
    public BigDecimal getEndBalCashEqu() {
        return endBalCashEqu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.end_bal_cash_equ
     *
     * @param endBalCashEqu the value for stk_finance_cashflow.end_bal_cash_equ
     *
     * @mbggenerated
     */
    public void setEndBalCashEqu(BigDecimal endBalCashEqu) {
        this.endBalCashEqu = endBalCashEqu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.beg_bal_cash_equ
     *
     * @return the value of stk_finance_cashflow.beg_bal_cash_equ
     *
     * @mbggenerated
     */
    public BigDecimal getBegBalCashEqu() {
        return begBalCashEqu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.beg_bal_cash_equ
     *
     * @param begBalCashEqu the value for stk_finance_cashflow.beg_bal_cash_equ
     *
     * @mbggenerated
     */
    public void setBegBalCashEqu(BigDecimal begBalCashEqu) {
        this.begBalCashEqu = begBalCashEqu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.im_n_incr_cash_equ
     *
     * @return the value of stk_finance_cashflow.im_n_incr_cash_equ
     *
     * @mbggenerated
     */
    public BigDecimal getImNIncrCashEqu() {
        return imNIncrCashEqu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.im_n_incr_cash_equ
     *
     * @param imNIncrCashEqu the value for stk_finance_cashflow.im_n_incr_cash_equ
     *
     * @mbggenerated
     */
    public void setImNIncrCashEqu(BigDecimal imNIncrCashEqu) {
        this.imNIncrCashEqu = imNIncrCashEqu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_cashflow.update_flag
     *
     * @return the value of stk_finance_cashflow.update_flag
     *
     * @mbggenerated
     */
    public String getUpdateFlag() {
        return updateFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_cashflow.update_flag
     *
     * @param updateFlag the value for stk_finance_cashflow.update_flag
     *
     * @mbggenerated
     */
    public void setUpdateFlag(String updateFlag) {
        this.updateFlag = updateFlag == null ? null : updateFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stk_finance_cashflow
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", tsCode=").append(tsCode);
        sb.append(", annDate=").append(annDate);
        sb.append(", fAnnDate=").append(fAnnDate);
        sb.append(", endDate=").append(endDate);
        sb.append(", reportType=").append(reportType);
        sb.append(", compType=").append(compType);
        sb.append(", netProfit=").append(netProfit);
        sb.append(", finanExp=").append(finanExp);
        sb.append(", cFrSaleSg=").append(cFrSaleSg);
        sb.append(", recpTaxRends=").append(recpTaxRends);
        sb.append(", nDeposIncrFi=").append(nDeposIncrFi);
        sb.append(", nIncrLoansCb=").append(nIncrLoansCb);
        sb.append(", nIncBorrOthFi=").append(nIncBorrOthFi);
        sb.append(", premFrOrigContr=").append(premFrOrigContr);
        sb.append(", nIncrInsuredDep=").append(nIncrInsuredDep);
        sb.append(", nReinsurPrem=").append(nReinsurPrem);
        sb.append(", nIncrDispTfa=").append(nIncrDispTfa);
        sb.append(", ifcCashIncr=").append(ifcCashIncr);
        sb.append(", nIncrDispFaas=").append(nIncrDispFaas);
        sb.append(", nIncrLoansOthBank=").append(nIncrLoansOthBank);
        sb.append(", nCapIncrRepur=").append(nCapIncrRepur);
        sb.append(", cFrOthOperateA=").append(cFrOthOperateA);
        sb.append(", cInfFrOperateA=").append(cInfFrOperateA);
        sb.append(", cPaidGoodsS=").append(cPaidGoodsS);
        sb.append(", cPaidToForEmpl=").append(cPaidToForEmpl);
        sb.append(", cPaidForTaxes=").append(cPaidForTaxes);
        sb.append(", nIncrCltLoanAdv=").append(nIncrCltLoanAdv);
        sb.append(", nIncrDepCbob=").append(nIncrDepCbob);
        sb.append(", cPayClaimsOrigInco=").append(cPayClaimsOrigInco);
        sb.append(", payHandlingChrg=").append(payHandlingChrg);
        sb.append(", payCommInsurPlcy=").append(payCommInsurPlcy);
        sb.append(", othCashPayOperAct=").append(othCashPayOperAct);
        sb.append(", stCashOutAct=").append(stCashOutAct);
        sb.append(", nCashflowAct=").append(nCashflowAct);
        sb.append(", othRecpRalInvAct=").append(othRecpRalInvAct);
        sb.append(", cDispWithdrwlInvest=").append(cDispWithdrwlInvest);
        sb.append(", cRecpReturnInvest=").append(cRecpReturnInvest);
        sb.append(", nRecpDispFiolta=").append(nRecpDispFiolta);
        sb.append(", nRecpDispSobu=").append(nRecpDispSobu);
        sb.append(", stotInflowsInvAct=").append(stotInflowsInvAct);
        sb.append(", cPayAcqConstFiolta=").append(cPayAcqConstFiolta);
        sb.append(", cPaidInvest=").append(cPaidInvest);
        sb.append(", nDispSubsOthBiz=").append(nDispSubsOthBiz);
        sb.append(", othPayRalInvAct=").append(othPayRalInvAct);
        sb.append(", nIncrPledgeLoan=").append(nIncrPledgeLoan);
        sb.append(", stotOutInvAct=").append(stotOutInvAct);
        sb.append(", nCashflowInvAct=").append(nCashflowInvAct);
        sb.append(", cRecpBorrow=").append(cRecpBorrow);
        sb.append(", procIssueBonds=").append(procIssueBonds);
        sb.append(", othCashRecpRalFncAct=").append(othCashRecpRalFncAct);
        sb.append(", stotCashInFncAct=").append(stotCashInFncAct);
        sb.append(", freeCashflow=").append(freeCashflow);
        sb.append(", cPrepayAmtBorr=").append(cPrepayAmtBorr);
        sb.append(", cPayDistDpcpIntExp=").append(cPayDistDpcpIntExp);
        sb.append(", inclDvdProfitPaidScMs=").append(inclDvdProfitPaidScMs);
        sb.append(", othCashpayRalFncAct=").append(othCashpayRalFncAct);
        sb.append(", stotCashoutFncAct=").append(stotCashoutFncAct);
        sb.append(", nCashFlowsFncAct=").append(nCashFlowsFncAct);
        sb.append(", effFxFluCash=").append(effFxFluCash);
        sb.append(", nIncrCashCashEqu=").append(nIncrCashCashEqu);
        sb.append(", cCashEquBegPeriod=").append(cCashEquBegPeriod);
        sb.append(", cCashEquEndPeriod=").append(cCashEquEndPeriod);
        sb.append(", cRecpCapContrib=").append(cRecpCapContrib);
        sb.append(", inclCashRecSaims=").append(inclCashRecSaims);
        sb.append(", unconInvestLoss=").append(unconInvestLoss);
        sb.append(", provDeprAssets=").append(provDeprAssets);
        sb.append(", deprFaCogaDpba=").append(deprFaCogaDpba);
        sb.append(", amortIntangAssets=").append(amortIntangAssets);
        sb.append(", ltAmortDeferredExp=").append(ltAmortDeferredExp);
        sb.append(", decrDeferredExp=").append(decrDeferredExp);
        sb.append(", incrAccExp=").append(incrAccExp);
        sb.append(", lossDispFiolta=").append(lossDispFiolta);
        sb.append(", lossScrFa=").append(lossScrFa);
        sb.append(", lossFvChg=").append(lossFvChg);
        sb.append(", investLoss=").append(investLoss);
        sb.append(", decrDefIncTaxAssets=").append(decrDefIncTaxAssets);
        sb.append(", incrDefIncTaxLiab=").append(incrDefIncTaxLiab);
        sb.append(", decrInventories=").append(decrInventories);
        sb.append(", decrOperPayable=").append(decrOperPayable);
        sb.append(", incrOperPayable=").append(incrOperPayable);
        sb.append(", others=").append(others);
        sb.append(", imNetCashflowOperAct=").append(imNetCashflowOperAct);
        sb.append(", convDebtIntoCap=").append(convDebtIntoCap);
        sb.append(", convCopbondsDueWithin1y=").append(convCopbondsDueWithin1y);
        sb.append(", faFncLeases=").append(faFncLeases);
        sb.append(", endBalCash=").append(endBalCash);
        sb.append(", begBalCash=").append(begBalCash);
        sb.append(", endBalCashEqu=").append(endBalCashEqu);
        sb.append(", begBalCashEqu=").append(begBalCashEqu);
        sb.append(", imNIncrCashEqu=").append(imNIncrCashEqu);
        sb.append(", updateFlag=").append(updateFlag);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}