package com.stock.info.domain.entity;

import java.io.Serializable;
import java.math.BigDecimal;

public class StkFinanceIncome implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_income.ts_code
     *
     * @mbggenerated
     */
    private String tsCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_income.ann_date
     *
     * @mbggenerated
     */
    private String annDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_income.f_ann_date
     *
     * @mbggenerated
     */
    private String fAnnDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_income.end_date
     *
     * @mbggenerated
     */
    private String endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_income.report_type
     *
     * @mbggenerated
     */
    private String reportType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_income.comp_type
     *
     * @mbggenerated
     */
    private String compType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_income.basic_eps
     *
     * @mbggenerated
     */
    private BigDecimal basicEps;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_income.diluted_eps
     *
     * @mbggenerated
     */
    private BigDecimal dilutedEps;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_income.total_revenue
     *
     * @mbggenerated
     */
    private BigDecimal totalRevenue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_income.revenue
     *
     * @mbggenerated
     */
    private BigDecimal revenue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_income.int_income
     *
     * @mbggenerated
     */
    private BigDecimal intIncome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_income.prem_earned
     *
     * @mbggenerated
     */
    private BigDecimal premEarned;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_income.comm_income
     *
     * @mbggenerated
     */
    private BigDecimal commIncome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_income.n_commis_income
     *
     * @mbggenerated
     */
    private BigDecimal nCommisIncome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_income.n_oth_income
     *
     * @mbggenerated
     */
    private BigDecimal nOthIncome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_income.n_oth_b_income
     *
     * @mbggenerated
     */
    private BigDecimal nOthBIncome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_income.prem_income
     *
     * @mbggenerated
     */
    private BigDecimal premIncome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_income.out_prem
     *
     * @mbggenerated
     */
    private BigDecimal outPrem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_income.une_prem_reser
     *
     * @mbggenerated
     */
    private BigDecimal unePremReser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_income.reins_income
     *
     * @mbggenerated
     */
    private BigDecimal reinsIncome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_income.n_sec_tb_income
     *
     * @mbggenerated
     */
    private BigDecimal nSecTbIncome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_income.n_sec_uw_income
     *
     * @mbggenerated
     */
    private BigDecimal nSecUwIncome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_income.n_asset_mg_income
     *
     * @mbggenerated
     */
    private BigDecimal nAssetMgIncome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_income.oth_b_income
     *
     * @mbggenerated
     */
    private BigDecimal othBIncome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_income.fv_value_chg_gain
     *
     * @mbggenerated
     */
    private BigDecimal fvValueChgGain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_income.invest_income
     *
     * @mbggenerated
     */
    private BigDecimal investIncome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_income.ass_invest_income
     *
     * @mbggenerated
     */
    private BigDecimal assInvestIncome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_income.forex_gain
     *
     * @mbggenerated
     */
    private BigDecimal forexGain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_income.total_cogs
     *
     * @mbggenerated
     */
    private BigDecimal totalCogs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_income.oper_cost
     *
     * @mbggenerated
     */
    private BigDecimal operCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_income.int_exp
     *
     * @mbggenerated
     */
    private BigDecimal intExp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_income.comm_exp
     *
     * @mbggenerated
     */
    private BigDecimal commExp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_income.biz_tax_surchg
     *
     * @mbggenerated
     */
    private BigDecimal bizTaxSurchg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_income.sell_exp
     *
     * @mbggenerated
     */
    private BigDecimal sellExp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_income.admin_exp
     *
     * @mbggenerated
     */
    private BigDecimal adminExp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_income.fin_exp
     *
     * @mbggenerated
     */
    private BigDecimal finExp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_income.assets_impair_loss
     *
     * @mbggenerated
     */
    private BigDecimal assetsImpairLoss;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_income.prem_refund
     *
     * @mbggenerated
     */
    private BigDecimal premRefund;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_income.compens_payout
     *
     * @mbggenerated
     */
    private BigDecimal compensPayout;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_income.reser_insur_liab
     *
     * @mbggenerated
     */
    private BigDecimal reserInsurLiab;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_income.div_payt
     *
     * @mbggenerated
     */
    private BigDecimal divPayt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_income.reins_exp
     *
     * @mbggenerated
     */
    private BigDecimal reinsExp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_income.oper_exp
     *
     * @mbggenerated
     */
    private BigDecimal operExp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_income.compens_payout_refu
     *
     * @mbggenerated
     */
    private BigDecimal compensPayoutRefu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_income.insur_reser_refu
     *
     * @mbggenerated
     */
    private BigDecimal insurReserRefu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_income.reins_cost_refund
     *
     * @mbggenerated
     */
    private BigDecimal reinsCostRefund;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_income.other_bus_cost
     *
     * @mbggenerated
     */
    private BigDecimal otherBusCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_income.operate_profit
     *
     * @mbggenerated
     */
    private BigDecimal operateProfit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_income.non_oper_income
     *
     * @mbggenerated
     */
    private BigDecimal nonOperIncome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_income.non_oper_exp
     *
     * @mbggenerated
     */
    private BigDecimal nonOperExp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_income.nca_disploss
     *
     * @mbggenerated
     */
    private BigDecimal ncaDisploss;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_income.total_profit
     *
     * @mbggenerated
     */
    private BigDecimal totalProfit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_income.income_tax
     *
     * @mbggenerated
     */
    private BigDecimal incomeTax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_income.n_income
     *
     * @mbggenerated
     */
    private BigDecimal nIncome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_income.n_income_attr_p
     *
     * @mbggenerated
     */
    private BigDecimal nIncomeAttrP;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_income.minority_gain
     *
     * @mbggenerated
     */
    private BigDecimal minorityGain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_income.oth_compr_income
     *
     * @mbggenerated
     */
    private BigDecimal othComprIncome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_income.t_compr_income
     *
     * @mbggenerated
     */
    private BigDecimal tComprIncome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_income.compr_inc_attr_p
     *
     * @mbggenerated
     */
    private BigDecimal comprIncAttrP;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_income.compr_inc_attr_m_s
     *
     * @mbggenerated
     */
    private BigDecimal comprIncAttrMS;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_income.ebit
     *
     * @mbggenerated
     */
    private BigDecimal ebit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_income.ebitda
     *
     * @mbggenerated
     */
    private BigDecimal ebitda;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_income.insurance_exp
     *
     * @mbggenerated
     */
    private BigDecimal insuranceExp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_income.undist_profit
     *
     * @mbggenerated
     */
    private BigDecimal undistProfit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_income.distable_profit
     *
     * @mbggenerated
     */
    private BigDecimal distableProfit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_income.update_flag
     *
     * @mbggenerated
     */
    private String updateFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table stk_finance_income
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_income.ts_code
     *
     * @return the value of stk_finance_income.ts_code
     *
     * @mbggenerated
     */
    public String getTsCode() {
        return tsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_income.ts_code
     *
     * @param tsCode the value for stk_finance_income.ts_code
     *
     * @mbggenerated
     */
    public void setTsCode(String tsCode) {
        this.tsCode = tsCode == null ? null : tsCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_income.ann_date
     *
     * @return the value of stk_finance_income.ann_date
     *
     * @mbggenerated
     */
    public String getAnnDate() {
        return annDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_income.ann_date
     *
     * @param annDate the value for stk_finance_income.ann_date
     *
     * @mbggenerated
     */
    public void setAnnDate(String annDate) {
        this.annDate = annDate == null ? null : annDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_income.f_ann_date
     *
     * @return the value of stk_finance_income.f_ann_date
     *
     * @mbggenerated
     */
    public String getfAnnDate() {
        return fAnnDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_income.f_ann_date
     *
     * @param fAnnDate the value for stk_finance_income.f_ann_date
     *
     * @mbggenerated
     */
    public void setfAnnDate(String fAnnDate) {
        this.fAnnDate = fAnnDate == null ? null : fAnnDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_income.end_date
     *
     * @return the value of stk_finance_income.end_date
     *
     * @mbggenerated
     */
    public String getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_income.end_date
     *
     * @param endDate the value for stk_finance_income.end_date
     *
     * @mbggenerated
     */
    public void setEndDate(String endDate) {
        this.endDate = endDate == null ? null : endDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_income.report_type
     *
     * @return the value of stk_finance_income.report_type
     *
     * @mbggenerated
     */
    public String getReportType() {
        return reportType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_income.report_type
     *
     * @param reportType the value for stk_finance_income.report_type
     *
     * @mbggenerated
     */
    public void setReportType(String reportType) {
        this.reportType = reportType == null ? null : reportType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_income.comp_type
     *
     * @return the value of stk_finance_income.comp_type
     *
     * @mbggenerated
     */
    public String getCompType() {
        return compType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_income.comp_type
     *
     * @param compType the value for stk_finance_income.comp_type
     *
     * @mbggenerated
     */
    public void setCompType(String compType) {
        this.compType = compType == null ? null : compType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_income.basic_eps
     *
     * @return the value of stk_finance_income.basic_eps
     *
     * @mbggenerated
     */
    public BigDecimal getBasicEps() {
        return basicEps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_income.basic_eps
     *
     * @param basicEps the value for stk_finance_income.basic_eps
     *
     * @mbggenerated
     */
    public void setBasicEps(BigDecimal basicEps) {
        this.basicEps = basicEps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_income.diluted_eps
     *
     * @return the value of stk_finance_income.diluted_eps
     *
     * @mbggenerated
     */
    public BigDecimal getDilutedEps() {
        return dilutedEps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_income.diluted_eps
     *
     * @param dilutedEps the value for stk_finance_income.diluted_eps
     *
     * @mbggenerated
     */
    public void setDilutedEps(BigDecimal dilutedEps) {
        this.dilutedEps = dilutedEps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_income.total_revenue
     *
     * @return the value of stk_finance_income.total_revenue
     *
     * @mbggenerated
     */
    public BigDecimal getTotalRevenue() {
        return totalRevenue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_income.total_revenue
     *
     * @param totalRevenue the value for stk_finance_income.total_revenue
     *
     * @mbggenerated
     */
    public void setTotalRevenue(BigDecimal totalRevenue) {
        this.totalRevenue = totalRevenue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_income.revenue
     *
     * @return the value of stk_finance_income.revenue
     *
     * @mbggenerated
     */
    public BigDecimal getRevenue() {
        return revenue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_income.revenue
     *
     * @param revenue the value for stk_finance_income.revenue
     *
     * @mbggenerated
     */
    public void setRevenue(BigDecimal revenue) {
        this.revenue = revenue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_income.int_income
     *
     * @return the value of stk_finance_income.int_income
     *
     * @mbggenerated
     */
    public BigDecimal getIntIncome() {
        return intIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_income.int_income
     *
     * @param intIncome the value for stk_finance_income.int_income
     *
     * @mbggenerated
     */
    public void setIntIncome(BigDecimal intIncome) {
        this.intIncome = intIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_income.prem_earned
     *
     * @return the value of stk_finance_income.prem_earned
     *
     * @mbggenerated
     */
    public BigDecimal getPremEarned() {
        return premEarned;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_income.prem_earned
     *
     * @param premEarned the value for stk_finance_income.prem_earned
     *
     * @mbggenerated
     */
    public void setPremEarned(BigDecimal premEarned) {
        this.premEarned = premEarned;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_income.comm_income
     *
     * @return the value of stk_finance_income.comm_income
     *
     * @mbggenerated
     */
    public BigDecimal getCommIncome() {
        return commIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_income.comm_income
     *
     * @param commIncome the value for stk_finance_income.comm_income
     *
     * @mbggenerated
     */
    public void setCommIncome(BigDecimal commIncome) {
        this.commIncome = commIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_income.n_commis_income
     *
     * @return the value of stk_finance_income.n_commis_income
     *
     * @mbggenerated
     */
    public BigDecimal getnCommisIncome() {
        return nCommisIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_income.n_commis_income
     *
     * @param nCommisIncome the value for stk_finance_income.n_commis_income
     *
     * @mbggenerated
     */
    public void setnCommisIncome(BigDecimal nCommisIncome) {
        this.nCommisIncome = nCommisIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_income.n_oth_income
     *
     * @return the value of stk_finance_income.n_oth_income
     *
     * @mbggenerated
     */
    public BigDecimal getnOthIncome() {
        return nOthIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_income.n_oth_income
     *
     * @param nOthIncome the value for stk_finance_income.n_oth_income
     *
     * @mbggenerated
     */
    public void setnOthIncome(BigDecimal nOthIncome) {
        this.nOthIncome = nOthIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_income.n_oth_b_income
     *
     * @return the value of stk_finance_income.n_oth_b_income
     *
     * @mbggenerated
     */
    public BigDecimal getnOthBIncome() {
        return nOthBIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_income.n_oth_b_income
     *
     * @param nOthBIncome the value for stk_finance_income.n_oth_b_income
     *
     * @mbggenerated
     */
    public void setnOthBIncome(BigDecimal nOthBIncome) {
        this.nOthBIncome = nOthBIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_income.prem_income
     *
     * @return the value of stk_finance_income.prem_income
     *
     * @mbggenerated
     */
    public BigDecimal getPremIncome() {
        return premIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_income.prem_income
     *
     * @param premIncome the value for stk_finance_income.prem_income
     *
     * @mbggenerated
     */
    public void setPremIncome(BigDecimal premIncome) {
        this.premIncome = premIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_income.out_prem
     *
     * @return the value of stk_finance_income.out_prem
     *
     * @mbggenerated
     */
    public BigDecimal getOutPrem() {
        return outPrem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_income.out_prem
     *
     * @param outPrem the value for stk_finance_income.out_prem
     *
     * @mbggenerated
     */
    public void setOutPrem(BigDecimal outPrem) {
        this.outPrem = outPrem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_income.une_prem_reser
     *
     * @return the value of stk_finance_income.une_prem_reser
     *
     * @mbggenerated
     */
    public BigDecimal getUnePremReser() {
        return unePremReser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_income.une_prem_reser
     *
     * @param unePremReser the value for stk_finance_income.une_prem_reser
     *
     * @mbggenerated
     */
    public void setUnePremReser(BigDecimal unePremReser) {
        this.unePremReser = unePremReser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_income.reins_income
     *
     * @return the value of stk_finance_income.reins_income
     *
     * @mbggenerated
     */
    public BigDecimal getReinsIncome() {
        return reinsIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_income.reins_income
     *
     * @param reinsIncome the value for stk_finance_income.reins_income
     *
     * @mbggenerated
     */
    public void setReinsIncome(BigDecimal reinsIncome) {
        this.reinsIncome = reinsIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_income.n_sec_tb_income
     *
     * @return the value of stk_finance_income.n_sec_tb_income
     *
     * @mbggenerated
     */
    public BigDecimal getnSecTbIncome() {
        return nSecTbIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_income.n_sec_tb_income
     *
     * @param nSecTbIncome the value for stk_finance_income.n_sec_tb_income
     *
     * @mbggenerated
     */
    public void setnSecTbIncome(BigDecimal nSecTbIncome) {
        this.nSecTbIncome = nSecTbIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_income.n_sec_uw_income
     *
     * @return the value of stk_finance_income.n_sec_uw_income
     *
     * @mbggenerated
     */
    public BigDecimal getnSecUwIncome() {
        return nSecUwIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_income.n_sec_uw_income
     *
     * @param nSecUwIncome the value for stk_finance_income.n_sec_uw_income
     *
     * @mbggenerated
     */
    public void setnSecUwIncome(BigDecimal nSecUwIncome) {
        this.nSecUwIncome = nSecUwIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_income.n_asset_mg_income
     *
     * @return the value of stk_finance_income.n_asset_mg_income
     *
     * @mbggenerated
     */
    public BigDecimal getnAssetMgIncome() {
        return nAssetMgIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_income.n_asset_mg_income
     *
     * @param nAssetMgIncome the value for stk_finance_income.n_asset_mg_income
     *
     * @mbggenerated
     */
    public void setnAssetMgIncome(BigDecimal nAssetMgIncome) {
        this.nAssetMgIncome = nAssetMgIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_income.oth_b_income
     *
     * @return the value of stk_finance_income.oth_b_income
     *
     * @mbggenerated
     */
    public BigDecimal getOthBIncome() {
        return othBIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_income.oth_b_income
     *
     * @param othBIncome the value for stk_finance_income.oth_b_income
     *
     * @mbggenerated
     */
    public void setOthBIncome(BigDecimal othBIncome) {
        this.othBIncome = othBIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_income.fv_value_chg_gain
     *
     * @return the value of stk_finance_income.fv_value_chg_gain
     *
     * @mbggenerated
     */
    public BigDecimal getFvValueChgGain() {
        return fvValueChgGain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_income.fv_value_chg_gain
     *
     * @param fvValueChgGain the value for stk_finance_income.fv_value_chg_gain
     *
     * @mbggenerated
     */
    public void setFvValueChgGain(BigDecimal fvValueChgGain) {
        this.fvValueChgGain = fvValueChgGain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_income.invest_income
     *
     * @return the value of stk_finance_income.invest_income
     *
     * @mbggenerated
     */
    public BigDecimal getInvestIncome() {
        return investIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_income.invest_income
     *
     * @param investIncome the value for stk_finance_income.invest_income
     *
     * @mbggenerated
     */
    public void setInvestIncome(BigDecimal investIncome) {
        this.investIncome = investIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_income.ass_invest_income
     *
     * @return the value of stk_finance_income.ass_invest_income
     *
     * @mbggenerated
     */
    public BigDecimal getAssInvestIncome() {
        return assInvestIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_income.ass_invest_income
     *
     * @param assInvestIncome the value for stk_finance_income.ass_invest_income
     *
     * @mbggenerated
     */
    public void setAssInvestIncome(BigDecimal assInvestIncome) {
        this.assInvestIncome = assInvestIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_income.forex_gain
     *
     * @return the value of stk_finance_income.forex_gain
     *
     * @mbggenerated
     */
    public BigDecimal getForexGain() {
        return forexGain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_income.forex_gain
     *
     * @param forexGain the value for stk_finance_income.forex_gain
     *
     * @mbggenerated
     */
    public void setForexGain(BigDecimal forexGain) {
        this.forexGain = forexGain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_income.total_cogs
     *
     * @return the value of stk_finance_income.total_cogs
     *
     * @mbggenerated
     */
    public BigDecimal getTotalCogs() {
        return totalCogs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_income.total_cogs
     *
     * @param totalCogs the value for stk_finance_income.total_cogs
     *
     * @mbggenerated
     */
    public void setTotalCogs(BigDecimal totalCogs) {
        this.totalCogs = totalCogs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_income.oper_cost
     *
     * @return the value of stk_finance_income.oper_cost
     *
     * @mbggenerated
     */
    public BigDecimal getOperCost() {
        return operCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_income.oper_cost
     *
     * @param operCost the value for stk_finance_income.oper_cost
     *
     * @mbggenerated
     */
    public void setOperCost(BigDecimal operCost) {
        this.operCost = operCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_income.int_exp
     *
     * @return the value of stk_finance_income.int_exp
     *
     * @mbggenerated
     */
    public BigDecimal getIntExp() {
        return intExp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_income.int_exp
     *
     * @param intExp the value for stk_finance_income.int_exp
     *
     * @mbggenerated
     */
    public void setIntExp(BigDecimal intExp) {
        this.intExp = intExp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_income.comm_exp
     *
     * @return the value of stk_finance_income.comm_exp
     *
     * @mbggenerated
     */
    public BigDecimal getCommExp() {
        return commExp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_income.comm_exp
     *
     * @param commExp the value for stk_finance_income.comm_exp
     *
     * @mbggenerated
     */
    public void setCommExp(BigDecimal commExp) {
        this.commExp = commExp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_income.biz_tax_surchg
     *
     * @return the value of stk_finance_income.biz_tax_surchg
     *
     * @mbggenerated
     */
    public BigDecimal getBizTaxSurchg() {
        return bizTaxSurchg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_income.biz_tax_surchg
     *
     * @param bizTaxSurchg the value for stk_finance_income.biz_tax_surchg
     *
     * @mbggenerated
     */
    public void setBizTaxSurchg(BigDecimal bizTaxSurchg) {
        this.bizTaxSurchg = bizTaxSurchg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_income.sell_exp
     *
     * @return the value of stk_finance_income.sell_exp
     *
     * @mbggenerated
     */
    public BigDecimal getSellExp() {
        return sellExp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_income.sell_exp
     *
     * @param sellExp the value for stk_finance_income.sell_exp
     *
     * @mbggenerated
     */
    public void setSellExp(BigDecimal sellExp) {
        this.sellExp = sellExp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_income.admin_exp
     *
     * @return the value of stk_finance_income.admin_exp
     *
     * @mbggenerated
     */
    public BigDecimal getAdminExp() {
        return adminExp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_income.admin_exp
     *
     * @param adminExp the value for stk_finance_income.admin_exp
     *
     * @mbggenerated
     */
    public void setAdminExp(BigDecimal adminExp) {
        this.adminExp = adminExp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_income.fin_exp
     *
     * @return the value of stk_finance_income.fin_exp
     *
     * @mbggenerated
     */
    public BigDecimal getFinExp() {
        return finExp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_income.fin_exp
     *
     * @param finExp the value for stk_finance_income.fin_exp
     *
     * @mbggenerated
     */
    public void setFinExp(BigDecimal finExp) {
        this.finExp = finExp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_income.assets_impair_loss
     *
     * @return the value of stk_finance_income.assets_impair_loss
     *
     * @mbggenerated
     */
    public BigDecimal getAssetsImpairLoss() {
        return assetsImpairLoss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_income.assets_impair_loss
     *
     * @param assetsImpairLoss the value for stk_finance_income.assets_impair_loss
     *
     * @mbggenerated
     */
    public void setAssetsImpairLoss(BigDecimal assetsImpairLoss) {
        this.assetsImpairLoss = assetsImpairLoss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_income.prem_refund
     *
     * @return the value of stk_finance_income.prem_refund
     *
     * @mbggenerated
     */
    public BigDecimal getPremRefund() {
        return premRefund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_income.prem_refund
     *
     * @param premRefund the value for stk_finance_income.prem_refund
     *
     * @mbggenerated
     */
    public void setPremRefund(BigDecimal premRefund) {
        this.premRefund = premRefund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_income.compens_payout
     *
     * @return the value of stk_finance_income.compens_payout
     *
     * @mbggenerated
     */
    public BigDecimal getCompensPayout() {
        return compensPayout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_income.compens_payout
     *
     * @param compensPayout the value for stk_finance_income.compens_payout
     *
     * @mbggenerated
     */
    public void setCompensPayout(BigDecimal compensPayout) {
        this.compensPayout = compensPayout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_income.reser_insur_liab
     *
     * @return the value of stk_finance_income.reser_insur_liab
     *
     * @mbggenerated
     */
    public BigDecimal getReserInsurLiab() {
        return reserInsurLiab;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_income.reser_insur_liab
     *
     * @param reserInsurLiab the value for stk_finance_income.reser_insur_liab
     *
     * @mbggenerated
     */
    public void setReserInsurLiab(BigDecimal reserInsurLiab) {
        this.reserInsurLiab = reserInsurLiab;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_income.div_payt
     *
     * @return the value of stk_finance_income.div_payt
     *
     * @mbggenerated
     */
    public BigDecimal getDivPayt() {
        return divPayt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_income.div_payt
     *
     * @param divPayt the value for stk_finance_income.div_payt
     *
     * @mbggenerated
     */
    public void setDivPayt(BigDecimal divPayt) {
        this.divPayt = divPayt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_income.reins_exp
     *
     * @return the value of stk_finance_income.reins_exp
     *
     * @mbggenerated
     */
    public BigDecimal getReinsExp() {
        return reinsExp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_income.reins_exp
     *
     * @param reinsExp the value for stk_finance_income.reins_exp
     *
     * @mbggenerated
     */
    public void setReinsExp(BigDecimal reinsExp) {
        this.reinsExp = reinsExp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_income.oper_exp
     *
     * @return the value of stk_finance_income.oper_exp
     *
     * @mbggenerated
     */
    public BigDecimal getOperExp() {
        return operExp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_income.oper_exp
     *
     * @param operExp the value for stk_finance_income.oper_exp
     *
     * @mbggenerated
     */
    public void setOperExp(BigDecimal operExp) {
        this.operExp = operExp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_income.compens_payout_refu
     *
     * @return the value of stk_finance_income.compens_payout_refu
     *
     * @mbggenerated
     */
    public BigDecimal getCompensPayoutRefu() {
        return compensPayoutRefu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_income.compens_payout_refu
     *
     * @param compensPayoutRefu the value for stk_finance_income.compens_payout_refu
     *
     * @mbggenerated
     */
    public void setCompensPayoutRefu(BigDecimal compensPayoutRefu) {
        this.compensPayoutRefu = compensPayoutRefu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_income.insur_reser_refu
     *
     * @return the value of stk_finance_income.insur_reser_refu
     *
     * @mbggenerated
     */
    public BigDecimal getInsurReserRefu() {
        return insurReserRefu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_income.insur_reser_refu
     *
     * @param insurReserRefu the value for stk_finance_income.insur_reser_refu
     *
     * @mbggenerated
     */
    public void setInsurReserRefu(BigDecimal insurReserRefu) {
        this.insurReserRefu = insurReserRefu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_income.reins_cost_refund
     *
     * @return the value of stk_finance_income.reins_cost_refund
     *
     * @mbggenerated
     */
    public BigDecimal getReinsCostRefund() {
        return reinsCostRefund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_income.reins_cost_refund
     *
     * @param reinsCostRefund the value for stk_finance_income.reins_cost_refund
     *
     * @mbggenerated
     */
    public void setReinsCostRefund(BigDecimal reinsCostRefund) {
        this.reinsCostRefund = reinsCostRefund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_income.other_bus_cost
     *
     * @return the value of stk_finance_income.other_bus_cost
     *
     * @mbggenerated
     */
    public BigDecimal getOtherBusCost() {
        return otherBusCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_income.other_bus_cost
     *
     * @param otherBusCost the value for stk_finance_income.other_bus_cost
     *
     * @mbggenerated
     */
    public void setOtherBusCost(BigDecimal otherBusCost) {
        this.otherBusCost = otherBusCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_income.operate_profit
     *
     * @return the value of stk_finance_income.operate_profit
     *
     * @mbggenerated
     */
    public BigDecimal getOperateProfit() {
        return operateProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_income.operate_profit
     *
     * @param operateProfit the value for stk_finance_income.operate_profit
     *
     * @mbggenerated
     */
    public void setOperateProfit(BigDecimal operateProfit) {
        this.operateProfit = operateProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_income.non_oper_income
     *
     * @return the value of stk_finance_income.non_oper_income
     *
     * @mbggenerated
     */
    public BigDecimal getNonOperIncome() {
        return nonOperIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_income.non_oper_income
     *
     * @param nonOperIncome the value for stk_finance_income.non_oper_income
     *
     * @mbggenerated
     */
    public void setNonOperIncome(BigDecimal nonOperIncome) {
        this.nonOperIncome = nonOperIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_income.non_oper_exp
     *
     * @return the value of stk_finance_income.non_oper_exp
     *
     * @mbggenerated
     */
    public BigDecimal getNonOperExp() {
        return nonOperExp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_income.non_oper_exp
     *
     * @param nonOperExp the value for stk_finance_income.non_oper_exp
     *
     * @mbggenerated
     */
    public void setNonOperExp(BigDecimal nonOperExp) {
        this.nonOperExp = nonOperExp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_income.nca_disploss
     *
     * @return the value of stk_finance_income.nca_disploss
     *
     * @mbggenerated
     */
    public BigDecimal getNcaDisploss() {
        return ncaDisploss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_income.nca_disploss
     *
     * @param ncaDisploss the value for stk_finance_income.nca_disploss
     *
     * @mbggenerated
     */
    public void setNcaDisploss(BigDecimal ncaDisploss) {
        this.ncaDisploss = ncaDisploss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_income.total_profit
     *
     * @return the value of stk_finance_income.total_profit
     *
     * @mbggenerated
     */
    public BigDecimal getTotalProfit() {
        return totalProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_income.total_profit
     *
     * @param totalProfit the value for stk_finance_income.total_profit
     *
     * @mbggenerated
     */
    public void setTotalProfit(BigDecimal totalProfit) {
        this.totalProfit = totalProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_income.income_tax
     *
     * @return the value of stk_finance_income.income_tax
     *
     * @mbggenerated
     */
    public BigDecimal getIncomeTax() {
        return incomeTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_income.income_tax
     *
     * @param incomeTax the value for stk_finance_income.income_tax
     *
     * @mbggenerated
     */
    public void setIncomeTax(BigDecimal incomeTax) {
        this.incomeTax = incomeTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_income.n_income
     *
     * @return the value of stk_finance_income.n_income
     *
     * @mbggenerated
     */
    public BigDecimal getnIncome() {
        return nIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_income.n_income
     *
     * @param nIncome the value for stk_finance_income.n_income
     *
     * @mbggenerated
     */
    public void setnIncome(BigDecimal nIncome) {
        this.nIncome = nIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_income.n_income_attr_p
     *
     * @return the value of stk_finance_income.n_income_attr_p
     *
     * @mbggenerated
     */
    public BigDecimal getnIncomeAttrP() {
        return nIncomeAttrP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_income.n_income_attr_p
     *
     * @param nIncomeAttrP the value for stk_finance_income.n_income_attr_p
     *
     * @mbggenerated
     */
    public void setnIncomeAttrP(BigDecimal nIncomeAttrP) {
        this.nIncomeAttrP = nIncomeAttrP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_income.minority_gain
     *
     * @return the value of stk_finance_income.minority_gain
     *
     * @mbggenerated
     */
    public BigDecimal getMinorityGain() {
        return minorityGain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_income.minority_gain
     *
     * @param minorityGain the value for stk_finance_income.minority_gain
     *
     * @mbggenerated
     */
    public void setMinorityGain(BigDecimal minorityGain) {
        this.minorityGain = minorityGain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_income.oth_compr_income
     *
     * @return the value of stk_finance_income.oth_compr_income
     *
     * @mbggenerated
     */
    public BigDecimal getOthComprIncome() {
        return othComprIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_income.oth_compr_income
     *
     * @param othComprIncome the value for stk_finance_income.oth_compr_income
     *
     * @mbggenerated
     */
    public void setOthComprIncome(BigDecimal othComprIncome) {
        this.othComprIncome = othComprIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_income.t_compr_income
     *
     * @return the value of stk_finance_income.t_compr_income
     *
     * @mbggenerated
     */
    public BigDecimal gettComprIncome() {
        return tComprIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_income.t_compr_income
     *
     * @param tComprIncome the value for stk_finance_income.t_compr_income
     *
     * @mbggenerated
     */
    public void settComprIncome(BigDecimal tComprIncome) {
        this.tComprIncome = tComprIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_income.compr_inc_attr_p
     *
     * @return the value of stk_finance_income.compr_inc_attr_p
     *
     * @mbggenerated
     */
    public BigDecimal getComprIncAttrP() {
        return comprIncAttrP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_income.compr_inc_attr_p
     *
     * @param comprIncAttrP the value for stk_finance_income.compr_inc_attr_p
     *
     * @mbggenerated
     */
    public void setComprIncAttrP(BigDecimal comprIncAttrP) {
        this.comprIncAttrP = comprIncAttrP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_income.compr_inc_attr_m_s
     *
     * @return the value of stk_finance_income.compr_inc_attr_m_s
     *
     * @mbggenerated
     */
    public BigDecimal getComprIncAttrMS() {
        return comprIncAttrMS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_income.compr_inc_attr_m_s
     *
     * @param comprIncAttrMS the value for stk_finance_income.compr_inc_attr_m_s
     *
     * @mbggenerated
     */
    public void setComprIncAttrMS(BigDecimal comprIncAttrMS) {
        this.comprIncAttrMS = comprIncAttrMS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_income.ebit
     *
     * @return the value of stk_finance_income.ebit
     *
     * @mbggenerated
     */
    public BigDecimal getEbit() {
        return ebit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_income.ebit
     *
     * @param ebit the value for stk_finance_income.ebit
     *
     * @mbggenerated
     */
    public void setEbit(BigDecimal ebit) {
        this.ebit = ebit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_income.ebitda
     *
     * @return the value of stk_finance_income.ebitda
     *
     * @mbggenerated
     */
    public BigDecimal getEbitda() {
        return ebitda;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_income.ebitda
     *
     * @param ebitda the value for stk_finance_income.ebitda
     *
     * @mbggenerated
     */
    public void setEbitda(BigDecimal ebitda) {
        this.ebitda = ebitda;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_income.insurance_exp
     *
     * @return the value of stk_finance_income.insurance_exp
     *
     * @mbggenerated
     */
    public BigDecimal getInsuranceExp() {
        return insuranceExp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_income.insurance_exp
     *
     * @param insuranceExp the value for stk_finance_income.insurance_exp
     *
     * @mbggenerated
     */
    public void setInsuranceExp(BigDecimal insuranceExp) {
        this.insuranceExp = insuranceExp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_income.undist_profit
     *
     * @return the value of stk_finance_income.undist_profit
     *
     * @mbggenerated
     */
    public BigDecimal getUndistProfit() {
        return undistProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_income.undist_profit
     *
     * @param undistProfit the value for stk_finance_income.undist_profit
     *
     * @mbggenerated
     */
    public void setUndistProfit(BigDecimal undistProfit) {
        this.undistProfit = undistProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_income.distable_profit
     *
     * @return the value of stk_finance_income.distable_profit
     *
     * @mbggenerated
     */
    public BigDecimal getDistableProfit() {
        return distableProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_income.distable_profit
     *
     * @param distableProfit the value for stk_finance_income.distable_profit
     *
     * @mbggenerated
     */
    public void setDistableProfit(BigDecimal distableProfit) {
        this.distableProfit = distableProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_income.update_flag
     *
     * @return the value of stk_finance_income.update_flag
     *
     * @mbggenerated
     */
    public String getUpdateFlag() {
        return updateFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_income.update_flag
     *
     * @param updateFlag the value for stk_finance_income.update_flag
     *
     * @mbggenerated
     */
    public void setUpdateFlag(String updateFlag) {
        this.updateFlag = updateFlag == null ? null : updateFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stk_finance_income
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", tsCode=").append(tsCode);
        sb.append(", annDate=").append(annDate);
        sb.append(", fAnnDate=").append(fAnnDate);
        sb.append(", endDate=").append(endDate);
        sb.append(", reportType=").append(reportType);
        sb.append(", compType=").append(compType);
        sb.append(", basicEps=").append(basicEps);
        sb.append(", dilutedEps=").append(dilutedEps);
        sb.append(", totalRevenue=").append(totalRevenue);
        sb.append(", revenue=").append(revenue);
        sb.append(", intIncome=").append(intIncome);
        sb.append(", premEarned=").append(premEarned);
        sb.append(", commIncome=").append(commIncome);
        sb.append(", nCommisIncome=").append(nCommisIncome);
        sb.append(", nOthIncome=").append(nOthIncome);
        sb.append(", nOthBIncome=").append(nOthBIncome);
        sb.append(", premIncome=").append(premIncome);
        sb.append(", outPrem=").append(outPrem);
        sb.append(", unePremReser=").append(unePremReser);
        sb.append(", reinsIncome=").append(reinsIncome);
        sb.append(", nSecTbIncome=").append(nSecTbIncome);
        sb.append(", nSecUwIncome=").append(nSecUwIncome);
        sb.append(", nAssetMgIncome=").append(nAssetMgIncome);
        sb.append(", othBIncome=").append(othBIncome);
        sb.append(", fvValueChgGain=").append(fvValueChgGain);
        sb.append(", investIncome=").append(investIncome);
        sb.append(", assInvestIncome=").append(assInvestIncome);
        sb.append(", forexGain=").append(forexGain);
        sb.append(", totalCogs=").append(totalCogs);
        sb.append(", operCost=").append(operCost);
        sb.append(", intExp=").append(intExp);
        sb.append(", commExp=").append(commExp);
        sb.append(", bizTaxSurchg=").append(bizTaxSurchg);
        sb.append(", sellExp=").append(sellExp);
        sb.append(", adminExp=").append(adminExp);
        sb.append(", finExp=").append(finExp);
        sb.append(", assetsImpairLoss=").append(assetsImpairLoss);
        sb.append(", premRefund=").append(premRefund);
        sb.append(", compensPayout=").append(compensPayout);
        sb.append(", reserInsurLiab=").append(reserInsurLiab);
        sb.append(", divPayt=").append(divPayt);
        sb.append(", reinsExp=").append(reinsExp);
        sb.append(", operExp=").append(operExp);
        sb.append(", compensPayoutRefu=").append(compensPayoutRefu);
        sb.append(", insurReserRefu=").append(insurReserRefu);
        sb.append(", reinsCostRefund=").append(reinsCostRefund);
        sb.append(", otherBusCost=").append(otherBusCost);
        sb.append(", operateProfit=").append(operateProfit);
        sb.append(", nonOperIncome=").append(nonOperIncome);
        sb.append(", nonOperExp=").append(nonOperExp);
        sb.append(", ncaDisploss=").append(ncaDisploss);
        sb.append(", totalProfit=").append(totalProfit);
        sb.append(", incomeTax=").append(incomeTax);
        sb.append(", nIncome=").append(nIncome);
        sb.append(", nIncomeAttrP=").append(nIncomeAttrP);
        sb.append(", minorityGain=").append(minorityGain);
        sb.append(", othComprIncome=").append(othComprIncome);
        sb.append(", tComprIncome=").append(tComprIncome);
        sb.append(", comprIncAttrP=").append(comprIncAttrP);
        sb.append(", comprIncAttrMS=").append(comprIncAttrMS);
        sb.append(", ebit=").append(ebit);
        sb.append(", ebitda=").append(ebitda);
        sb.append(", insuranceExp=").append(insuranceExp);
        sb.append(", undistProfit=").append(undistProfit);
        sb.append(", distableProfit=").append(distableProfit);
        sb.append(", updateFlag=").append(updateFlag);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}