package com.stock.info.domain.entity;

import java.io.Serializable;
import java.math.BigDecimal;

public class StkFinanceMainbz implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_mainbz.ts_code
     *
     * @mbggenerated
     */
    private String tsCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_mainbz.end_date
     *
     * @mbggenerated
     */
    private String endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_mainbz.bz_item
     *
     * @mbggenerated
     */
    private String bzItem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_mainbz.bz_sales
     *
     * @mbggenerated
     */
    private BigDecimal bzSales;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_mainbz.bz_profit
     *
     * @mbggenerated
     */
    private BigDecimal bzProfit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_mainbz.bz_cost
     *
     * @mbggenerated
     */
    private BigDecimal bzCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_mainbz.curr_type
     *
     * @mbggenerated
     */
    private String currType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_finance_mainbz.update_flag
     *
     * @mbggenerated
     */
    private String updateFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table stk_finance_mainbz
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_mainbz.ts_code
     *
     * @return the value of stk_finance_mainbz.ts_code
     *
     * @mbggenerated
     */
    public String getTsCode() {
        return tsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_mainbz.ts_code
     *
     * @param tsCode the value for stk_finance_mainbz.ts_code
     *
     * @mbggenerated
     */
    public void setTsCode(String tsCode) {
        this.tsCode = tsCode == null ? null : tsCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_mainbz.end_date
     *
     * @return the value of stk_finance_mainbz.end_date
     *
     * @mbggenerated
     */
    public String getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_mainbz.end_date
     *
     * @param endDate the value for stk_finance_mainbz.end_date
     *
     * @mbggenerated
     */
    public void setEndDate(String endDate) {
        this.endDate = endDate == null ? null : endDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_mainbz.bz_item
     *
     * @return the value of stk_finance_mainbz.bz_item
     *
     * @mbggenerated
     */
    public String getBzItem() {
        return bzItem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_mainbz.bz_item
     *
     * @param bzItem the value for stk_finance_mainbz.bz_item
     *
     * @mbggenerated
     */
    public void setBzItem(String bzItem) {
        this.bzItem = bzItem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_mainbz.bz_sales
     *
     * @return the value of stk_finance_mainbz.bz_sales
     *
     * @mbggenerated
     */
    public BigDecimal getBzSales() {
        return bzSales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_mainbz.bz_sales
     *
     * @param bzSales the value for stk_finance_mainbz.bz_sales
     *
     * @mbggenerated
     */
    public void setBzSales(BigDecimal bzSales) {
        this.bzSales = bzSales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_mainbz.bz_profit
     *
     * @return the value of stk_finance_mainbz.bz_profit
     *
     * @mbggenerated
     */
    public BigDecimal getBzProfit() {
        return bzProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_mainbz.bz_profit
     *
     * @param bzProfit the value for stk_finance_mainbz.bz_profit
     *
     * @mbggenerated
     */
    public void setBzProfit(BigDecimal bzProfit) {
        this.bzProfit = bzProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_mainbz.bz_cost
     *
     * @return the value of stk_finance_mainbz.bz_cost
     *
     * @mbggenerated
     */
    public BigDecimal getBzCost() {
        return bzCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_mainbz.bz_cost
     *
     * @param bzCost the value for stk_finance_mainbz.bz_cost
     *
     * @mbggenerated
     */
    public void setBzCost(BigDecimal bzCost) {
        this.bzCost = bzCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_mainbz.curr_type
     *
     * @return the value of stk_finance_mainbz.curr_type
     *
     * @mbggenerated
     */
    public String getCurrType() {
        return currType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_mainbz.curr_type
     *
     * @param currType the value for stk_finance_mainbz.curr_type
     *
     * @mbggenerated
     */
    public void setCurrType(String currType) {
        this.currType = currType == null ? null : currType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_finance_mainbz.update_flag
     *
     * @return the value of stk_finance_mainbz.update_flag
     *
     * @mbggenerated
     */
    public String getUpdateFlag() {
        return updateFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_finance_mainbz.update_flag
     *
     * @param updateFlag the value for stk_finance_mainbz.update_flag
     *
     * @mbggenerated
     */
    public void setUpdateFlag(String updateFlag) {
        this.updateFlag = updateFlag == null ? null : updateFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stk_finance_mainbz
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", tsCode=").append(tsCode);
        sb.append(", endDate=").append(endDate);
        sb.append(", bzItem=").append(bzItem);
        sb.append(", bzSales=").append(bzSales);
        sb.append(", bzProfit=").append(bzProfit);
        sb.append(", bzCost=").append(bzCost);
        sb.append(", currType=").append(currType);
        sb.append(", updateFlag=").append(updateFlag);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}