package com.stock.info.domain.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class StkMarketPriceMonthly implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_market_price_monthly.ts_code
     *
     * @mbggenerated
     */
    private String tsCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_market_price_monthly.trade_date
     *
     * @mbggenerated
     */
    private String tradeDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_market_price_monthly.close
     *
     * @mbggenerated
     */
    private BigDecimal close;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_market_price_monthly.open
     *
     * @mbggenerated
     */
    private BigDecimal open;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_market_price_monthly.high
     *
     * @mbggenerated
     */
    private BigDecimal high;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_market_price_monthly.low
     *
     * @mbggenerated
     */
    private BigDecimal low;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_market_price_monthly.pre_close
     *
     * @mbggenerated
     */
    private BigDecimal preClose;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_market_price_monthly.change
     *
     * @mbggenerated
     */
    private BigDecimal change;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_market_price_monthly.pct_chg
     *
     * @mbggenerated
     */
    private BigDecimal pctChg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_market_price_monthly.vol
     *
     * @mbggenerated
     */
    private BigDecimal vol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_market_price_monthly.amount
     *
     * @mbggenerated
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stk_market_price_monthly.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table stk_market_price_monthly
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_market_price_monthly.ts_code
     *
     * @return the value of stk_market_price_monthly.ts_code
     *
     * @mbggenerated
     */
    public String getTsCode() {
        return tsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_market_price_monthly.ts_code
     *
     * @param tsCode the value for stk_market_price_monthly.ts_code
     *
     * @mbggenerated
     */
    public void setTsCode(String tsCode) {
        this.tsCode = tsCode == null ? null : tsCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_market_price_monthly.trade_date
     *
     * @return the value of stk_market_price_monthly.trade_date
     *
     * @mbggenerated
     */
    public String getTradeDate() {
        return tradeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_market_price_monthly.trade_date
     *
     * @param tradeDate the value for stk_market_price_monthly.trade_date
     *
     * @mbggenerated
     */
    public void setTradeDate(String tradeDate) {
        this.tradeDate = tradeDate == null ? null : tradeDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_market_price_monthly.close
     *
     * @return the value of stk_market_price_monthly.close
     *
     * @mbggenerated
     */
    public BigDecimal getClose() {
        return close;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_market_price_monthly.close
     *
     * @param close the value for stk_market_price_monthly.close
     *
     * @mbggenerated
     */
    public void setClose(BigDecimal close) {
        this.close = close;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_market_price_monthly.open
     *
     * @return the value of stk_market_price_monthly.open
     *
     * @mbggenerated
     */
    public BigDecimal getOpen() {
        return open;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_market_price_monthly.open
     *
     * @param open the value for stk_market_price_monthly.open
     *
     * @mbggenerated
     */
    public void setOpen(BigDecimal open) {
        this.open = open;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_market_price_monthly.high
     *
     * @return the value of stk_market_price_monthly.high
     *
     * @mbggenerated
     */
    public BigDecimal getHigh() {
        return high;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_market_price_monthly.high
     *
     * @param high the value for stk_market_price_monthly.high
     *
     * @mbggenerated
     */
    public void setHigh(BigDecimal high) {
        this.high = high;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_market_price_monthly.low
     *
     * @return the value of stk_market_price_monthly.low
     *
     * @mbggenerated
     */
    public BigDecimal getLow() {
        return low;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_market_price_monthly.low
     *
     * @param low the value for stk_market_price_monthly.low
     *
     * @mbggenerated
     */
    public void setLow(BigDecimal low) {
        this.low = low;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_market_price_monthly.pre_close
     *
     * @return the value of stk_market_price_monthly.pre_close
     *
     * @mbggenerated
     */
    public BigDecimal getPreClose() {
        return preClose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_market_price_monthly.pre_close
     *
     * @param preClose the value for stk_market_price_monthly.pre_close
     *
     * @mbggenerated
     */
    public void setPreClose(BigDecimal preClose) {
        this.preClose = preClose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_market_price_monthly.change
     *
     * @return the value of stk_market_price_monthly.change
     *
     * @mbggenerated
     */
    public BigDecimal getChange() {
        return change;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_market_price_monthly.change
     *
     * @param change the value for stk_market_price_monthly.change
     *
     * @mbggenerated
     */
    public void setChange(BigDecimal change) {
        this.change = change;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_market_price_monthly.pct_chg
     *
     * @return the value of stk_market_price_monthly.pct_chg
     *
     * @mbggenerated
     */
    public BigDecimal getPctChg() {
        return pctChg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_market_price_monthly.pct_chg
     *
     * @param pctChg the value for stk_market_price_monthly.pct_chg
     *
     * @mbggenerated
     */
    public void setPctChg(BigDecimal pctChg) {
        this.pctChg = pctChg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_market_price_monthly.vol
     *
     * @return the value of stk_market_price_monthly.vol
     *
     * @mbggenerated
     */
    public BigDecimal getVol() {
        return vol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_market_price_monthly.vol
     *
     * @param vol the value for stk_market_price_monthly.vol
     *
     * @mbggenerated
     */
    public void setVol(BigDecimal vol) {
        this.vol = vol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_market_price_monthly.amount
     *
     * @return the value of stk_market_price_monthly.amount
     *
     * @mbggenerated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_market_price_monthly.amount
     *
     * @param amount the value for stk_market_price_monthly.amount
     *
     * @mbggenerated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stk_market_price_monthly.create_date
     *
     * @return the value of stk_market_price_monthly.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stk_market_price_monthly.create_date
     *
     * @param createDate the value for stk_market_price_monthly.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stk_market_price_monthly
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", tsCode=").append(tsCode);
        sb.append(", tradeDate=").append(tradeDate);
        sb.append(", close=").append(close);
        sb.append(", open=").append(open);
        sb.append(", high=").append(high);
        sb.append(", low=").append(low);
        sb.append(", preClose=").append(preClose);
        sb.append(", change=").append(change);
        sb.append(", pctChg=").append(pctChg);
        sb.append(", vol=").append(vol);
        sb.append(", amount=").append(amount);
        sb.append(", createDate=").append(createDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}